### ISSUE TITLE
Rocket API related exception

### ISSUE THREAD

**Issue by t-p-l-k** [NECROBOTIO/NecroBot#1894]
Running 6 instances of v0.5.0. Sometimes one or another instance crushes with the following error.

`Unhandled Exception: PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException: Exception of type 'PokemonGo.RocketAPI.Exceptions.AccessTokenExpiredException' was thrown.
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__3.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoPtcLogin>d__2.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 65
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()`

**Comment by recon88** [comment]
You can report API issues here: https://github.com/NECROBOTIO/NecroBot-Rocket-API/tree/master
