### ISSUE TITLE
Manual Sniping Error

### ISSUE THREAD

**Issue by freyying1234** [NECROBOTIO/NecroBot#2004]
I have issues using the manual sniping config. The following is the sniping error log I am getting; is it normal for it to try to connect to localhost at port 8888?

[00:06:46] Scanning for Snipeable Pokemon at 38.5568074864611,-121.238379478455...
[00:06:47] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[00:06:47] No Pokemon found to snipe!
[00:06:47] Scanning for Snipeable Pokemon at -33.859019,151.213098...
[00:06:48] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[00:06:48] No Pokemon found to snipe!
[00:06:48] Scanning for Snipeable Pokemon at 47.5014969,-122.0959568...
[00:06:50] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[00:06:50] No Pokemon found to snipe!
[00:06:50] Scanning for Snipeable Pokemon at 51.5025343,-0.2055027...
[00:06:51] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[00:06:51] No Pokemon found to snipe!
[00:06:51] Scanning for Snipeable Pokemon at 49.268919,-122.880519...
[00:06:52] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[00:06:52] No Pokemon found to snipe!
[00:06:52] Scanning for Snipeable Pokemon at 22.29614,114.174575...
[00:06:53] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[00:06:53] No Pokemon found to snipe!
[00:06:53] Scanning for Snipeable Pokemon at 46.2479,20.14704...
[00:06:54] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[00:06:54] No Pokemon found to snipe!
[00:06:54] Scanning for Snipeable Pokemon at -33.9136269706758,151.267731785774...
[00:06:55] System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8888
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.SnipeScanForPokemon(ISession session, Location location) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 346
[00:06:55] No Pokemon found to snipe!

This is my config setting:

  "UseSnipeOnlineLocationServer": false,
  "UseSnipeLocationServer": false,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": true,
  "SnipeIgnoreUnknownIv": false,

**Comment by Wcidd** [comment]
Hi, you need to specify if you want to use a local server or online server, the online servers need to be updated and wont work untill update
https://github.com/NECROBOTIO/NecroBot/wiki/Automatic-Locations-Sniping-Guide

**Comment by freyying1234** [comment]
I am trying to use the manual location setup guide to setup sniping by following the manual locations sniping guide but it just give me this error. So is the manual sniping not working or I am not setting it up correctly.
