### ISSUE TITLE
Debug Error

### ISSUE THREAD

**Issue by KingDmetri** [NECROBOTIO/NecroBot#2007]
Index out of bounds error  during _GetPokeDexCount_ when a pokemon is seen but not caught.
Text shows **"timesEncountered"** instead of **"timesCaptured"**. Line 21 expects only **"timesCaptured"**.

Can be fixed with a simple if(CaughtPokemon.Length >1) block around line 22 to 25.

(Or "timesEncountered"can be accounted for, but an if will suffice.)
`[09:44:02] (ERROR) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PoGo.NecroBot.Logic.Tasks.GetPokeDexCount.<Execute>d__0.MoveNext() in .\NecroBot\PoGo.NecroBot.Logic\Tasks\GetPokeDexCount.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in .\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in .\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
[09:44:02] (ERROR) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PoGo.NecroBot.Logic.Tasks.GetPokeDexCount.<Execute>d__0.MoveNext() in .\NecroBot\PoGo.NecroBot.Logic\Tasks\GetPokeDexCount.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in .\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in .\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36`

**Comment by Oolaruu** [comment]
Feel free to go ahead to submit a Pull Request if that fixed your issue.

**Comment by KingDmetri** [comment]
No Longer relevant, 
Implementation changed to 
`var _totalUniqueEncounters = PokeDex.Select(i => new { Pokemon = i.InventoryItemData.PokedexEntry.PokemonId, Captures = i.InventoryItemData.PokedexEntry.TimesCaptured });
            var _totalCaptures = _totalUniqueEncounters.Count(i => i.Captures > 0);`
