### ISSUE TITLE
Necrobot Crashes on Startup - Unhandled Exception Error

### ISSUE THREAD

**Issue by Raymandude** [NECROBOTIO/NecroBot#2139]
[14:05:16] () Exceptiion caught, writing LogBuffer.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.Common.Translation.<>c__DisplayClass5_0.<Load>b__2(KeyValuePair`2 item) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Common\Translations.cs:line 569
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Common.Translation.Load(ILogicSettings logicSettings) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\Common\Translations.cs:line 0
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.Logic\State\Session.cs:line 32
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\tvgfx\Documents\Pokemon Go Bot\PoGo.NecroBot.CLI\Program.cs:line 51****

**Comment by Sylencer90** [comment]
check for typo's,

**Comment by NecronomiconCoding** [comment]
If this is still an issue in 0.6.2, please submit a new issue with enough details to reproduce.
