### ISSUE TITLE
Error/auto restarting idk what its doing

### ISSUE THREAD

**Issue by Alterium** [NECROBOTIO/NecroBot#2625]
Bassicly this keeps happening : 

[20:50:03] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<>c__DisplayClass0_1.<Execute>b__1(Candy q) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 46
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
[20:50:04] (INFO) Logging in using Google

If you need my logs i can give you those if you need them
And yes i already tried re-downloading the bot.

**Comment by brokenHDD** [comment]
Seems to be a server issue, many people are experiencing the same problem but the tickets keep getting closed.

**Comment by Alterium** [comment]
Alright.
