### ISSUE TITLE
[ISSUE v0.6.4] Bot Crashing

### ISSUE THREAD

**Issue by AuliaYF** [NECROBOTIO/NecroBot#2631]
`
System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
`

**Comment by thisKeeWord** [comment]
I'm getting this too. need update!

**Comment by dislick** [comment]
Same here! Clean download of 0.6.4 and using a Google account. Default settings.

```
[21:10:15] [Evolves] Potential Evolves: 0
[21:10:16] Bellsprout	- CP: 572  IV: 33.90%   [Best CP: 764  IV: 63.93%] (Candies: 90)
[21:10:21] Zubat	- CP: 305  IV: 54.61%   [Best CP: 467  IV: 78.97%] (Candies: 1267)
[21:10:27] Slowbro	- CP: 1120  IV: 60.11%   [Best CP: 1461  IV: 40.81%] (Candies: 239)
[21:10:31] Psyduck	- CP: 214  IV: 33.07%   [Best CP: 771  IV: 53.58%] (Candies: 481)
[21:10:37] Lickitung	- CP: 575  IV: 73.30%   [Best CP: 927  IV: 72.21%] (Candies: 11)
[21:10:43] Amount of Pokemon Seen: 113/151, Amount of Pokemon Caught: 112/151
[21:10:43] Current Pokeballs: 31 | Greatballs: 96 | Ultraballs: 0 | Masterballs: 0
[21:10:43] Current Total Potions: 49 | Total Revives: 51 | Berries: 45 | Total Incense: 0 | Lucky Eggs: 0 | Lures: 5
[21:10:43] Incubator status update: 1.50km left
[21:10:44] Traveling to Pokestop: Frischhans Theiling (22m)(2seconds)
[21:10:44] Looking for Pokemon...
[21:10:45] Looking for incense Pokemon...
[21:10:46] Looking for lure Pokemon...
[21:10:48] (CatchEscape) | (Lure) Psyduck Lvl: 9 CP: (231/283) IV: 13.00% | Chance: 50.05% | 12.70m dist | with a PokeBall (30 left). |  | lat: 47.053104 long: 8.306628
[21:10:51] System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PoGo.NecroBot.Logic.Inventory.<GetItems>d__20.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:Zeile 252.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.Inventory.<GetItemAmountByType>d__19.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:Zeile 246.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CallSite.Target(Closure , CallSite , Object )
   bei PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:Zeile 243.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchLurePokemonsTask.cs:Zeile 43.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:Zeile 96.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:Zeile 69.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 36.
[21:10:51] Logging in using Google
```

**Comment by pernahajder** [comment]
change the option in config.json "GetOnlyVerifiedSniperInfoFromPokezz" to false

**Comment by Autobotuser** [comment]
doesn't work

**Comment by thisKeeWord** [comment]
my error seems to happen after it checks (and recycles) items
