### ISSUE TITLE
translation logic? bug on latest

### ISSUE THREAD

**Issue by toquengtoketin** [NECROBOTIO/NecroBot#2829]
Just ran into this and not sure what had happened

[img]
https://is.gd/Qq6N3x

[08:44:48]` (UPDATE) Perfect! You already have the newest Version 0.7.1
[08:44:48] (INFO) Logging in using Ptc
[08:44:51] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at POGOProtos.Networking.Signature.Types.DeviceInfo.set_DeviceId(String value) in C:\Users\[redacted]\Documents\Visual Studio 2015\Projects\NecroBot-master\POGOProtos\POGOProtos\Networking\Signature.cs:line 2126
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(IEnumerable`1 requests) in C:\Users\[redacted]\Documents\Visual Studio 2015\Projects\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 65
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(Request[] customRequests) in C:\Users\[redacted]\Documents\Visual Studio 2015\Projects\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 165
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(RequestType type, IMessage message) in C:\Users\[redacted]\Documents\Visual Studio 2015\Projects\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 200
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\[redacted]\Documents\Visual Studio 2015\Projects\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() in C:\Users\[redacted]\Documents\Visual Studio 2015\Projects\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in C:\Users\[redacted]\Documents\Visual Studio 2015\Projects\NecroBot-master\PoGo.NecroBot.Logic\State\LoginState.cs:line 181
[08:45:11] (ATTENTION) Due to login failure your player profile could not be retrieved. Press any key to re-try login.

**Comment by aapikz** [comment]
same error

**Comment by qbm5** [comment]
Same here, where are we suppose to get these values from
