### ISSUE TITLE
[ERROR]login fails due to google account selection

### ISSUE THREAD

**Issue by johnsilvavlogs** [NECROBOTIO/NecroBot#2852]
Hello! Every time I have to authorize an app, as it was for other bots, I had to manually select my account on google. because I am an owner of a Youtube Page and it prompts me to select or my google plus account or my YT page before I concede permissions for an app. I think that it why I am getting this log in error as follows:

[13:48:08] (INFO) Logging in using Google
[13:48:09] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
   at POGOProtos.Networking.Signature.Types.DeviceInfo.set_DeviceId(String value) in C:\Users\John\Downloads\NecroBot-master (13)\NecroBot-master\POGOProtos\POGOProtos\Networking\Signature.cs:line 2126
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GenerateSignature(IEnumerable`1 requests) in C:\Users\John\Downloads\NecroBot-master (13)\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 65
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(Request[] customRequests) in C:\Users\John\Downloads\NecroBot-master (13)\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 165
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.GetRequestEnvelope(RequestType type, IMessage message) in C:\Users\John\Downloads\NecroBot-master (13)\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 200
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__6`2.MoveNext() in C:\Users\John\Downloads\NecroBot-master (13)\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Rpc.Player.<GetPlayer>d__3.MoveNext() in C:\Users\John\Downloads\NecroBot-master (13)\NecroBot-master\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.LoginState.<DownloadProfile>d__2.MoveNext() in C:\Users\John\Downloads\NecroBot-master (13)\NecroBot-master\PoGo.NecroBot.Logic\State\LoginState.cs:line 181

**Comment by TrurlMcByte** [comment]
copy "DeviceId"..."FirmwareFingerprint" part from config.json to auth.json
