### ISSUE TITLE
Sudden Crash 

### ISSUE THREAD

**Issue by hellnest** [NECROBOTIO/NecroBot#2894]
[01:42:18] () Exceptiion caught, writing LogBuffer.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.ClientSettings.PokemonGo.RocketAPI.ISettings.get_DefaultAltitude() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 1095
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy apiFailureStrategy) in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Client.cs:line 60
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:line 53
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:line 32
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.CLI\Program.cs:line 77

**Comment by KevHart95** [comment]
#2900

**Comment by AussieMatt** [comment]
Just started doing this for me to, I also noticed that I would have to log back in with google.
