### ISSUE TITLE
No usable pokemon stop found in your area.

### ISSUE THREAD

**Issue by Zoast** [NECROBOTIO/NecroBot#2905]
I'm getting this message after running the bot for like 5-10 minutes. Then I have to restart the bot a couple of times and it works again. My distance is set to 1250 and I'm using the 6 stop as my starting location. I'm not sure if it's because I'm using wrong coordinates or something else. Does anyone perhaps  have coordinates where they seem to be able to run the bot consistently without restarting it?

**Comment by pythoneer** [comment]
2893

**Comment by GummiBoat** [comment]
From my "LastPos.ini" 

45.0325375043936:-93.3193101339426

**Comment by SDMU** [comment]
#2893

**Comment by Zoast** [comment]
@pythoneer and @SDMU

I am using 0.7.1. It works fine then just stops finding them. Seems like a different thing going on.

@GummiBoat 
It seems almost exactly the same as my position, but I'll give it a try, thanks!

**Comment by SDMU** [comment]
@Zoast what happens if you set a busy location as your default co ords . do you still get the same error ?

**Comment by Zoast** [comment]
@SDMU Sorry if I wasn't clear in my initial post. The bot works perfectly for approximately 10 minutes (default location is a busy point) but after 10 minutes it stops finding the pokestops. When I restart the bot two or three times, it starts over at my default position and the cycle repeats itself again. I hope I could make it clear.

**Comment by furiousbuilder** [comment]
Same bug for me, I botted all the afternoon, but now 2 of my accounts in France are getting this error on 0.7.2. My account that is botting in New York (central park) is still working

**Comment by Zoast** [comment]
@furiousbuilder Could you perhaps share the coordinates of your New York bot so I could test it out as well? Have you been running the bot since afternoon, without a single restart?

**Comment by furiousbuilder** [comment]
@Zoast : 40.783035,  -73.965473
I think the new API need an update, I personnaly think that a variable linked to GPS coordinates isn't generating a good value each time. The bot needs few reboots to be working. After 3 closes the bot is working fine now in Paris too.

**Comment by Zoast** [comment]
@furiousbuilder Thanks for the insight. I guess we'll have to keep an eye on the bot and manually restart it once in a while. I'll try out the Central Park coordinates as well and see how long I can keep the bot running consecutively. Once again, thanks!

**Comment by furiousbuilder** [comment]
If you want, I use AutoRestarter v1.7, it's restarting my bot every 30 minutes to avoid any bugs like that :) 
As a suggestion to the devs : as some of us are using an external restarter it should be great to add a settings which disable update confirmation as the restarter is unable to inject "y" automatically :)

**Comment by Zoast** [comment]
@furiousbuilder That's a great idea! Where could I get AutoRestarter?

**Comment by furiousbuilder** [comment]
@Zoast : I personnaly use this one : http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/566855-autobotsrestarter-multibot-nowindow-timed-restart-crashed.html

**Comment by lordoflies** [comment]
The config file does not include an altitude information now. Might this be the cause ?

**Comment by furiousbuilder** [comment]
The bot is getting altitude from google map to imitate a real GPS

**Comment by lordoflies** [comment]
I mean, might that be the cause ? Because in the 7.0.0 and 7.0.1 versions , I did change the altitude to 1030 (where my latlong corrseponds to) and the bot did not work. I changed it to 10 (default) and it worked that time.

**Comment by furiousbuilder** [comment]
I got this issue in 0.7.2, altitude set to 35 and 10, and as I know Niantic don't verify altitude for now, maybe a developper will be able to explain this to us :)

**Comment by furiousbuilder** [comment]
There definitely is an issue with the GPS : 
```
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
```

I'm getting this with my 3 accounts

**Comment by Zoast** [comment]
@furiousbuilder Have you been able to figure it out? I'm using 0.7.0 since my last post + the AutoRestart and things have been going great so far. Perhaps try using an older version, do not alter the altitude and things should work. I've been using your central park coordinates by the way.
