### ISSUE TITLE
PTC/Google update logging issue fix

### ISSUE THREAD

**Issue by Kendama165** [NECROBOTIO/NecroBot#2908]
go into the config and turn off autoupdate until the issue is fixed. Simple as that.

https://gyazo.com/eac17335f1e443e5fa1aeb26774ecf4f

Enjoy

**Comment by wetshrimp** [comment]
why

**Comment by Kendama165** [comment]
if it says you need to update and you skip it, it will auto use google,

**Comment by hellnest** [comment]
wow ok it work for google too.

**Comment by hellnest** [comment]
but still got disconnected suddenly

[02:04:38] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
[02:04:38] (INFO) Logging in using Google
[02:04:39] (INFO) Playing as UlunBogor
[02:04:39] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: -1.27660722764956 Lng: 116.834201603111
[02:04:40] (INFO) ====== DisplayHighestsCP ======
[02:04:40] (INFO) # CP 1094/1155 | (66.74% perfect)     | Lvl 20         NAME: Scyther           MOVE1: SteelWingFast        MOVE2: BugBuzz              Candy: 1
[02:04:40] (INFO) # CP  870/ 938 | (45.97% perfect)     | Lvl 11         NAME: Arcanine          MOVE1: BiteFast             MOVE2: Flamethrower         Candy: 33
[02:04:40] (INFO) # CP  752/ 779 | (81.44% perfect)     | Lvl 18         NAME: Ponyta            MOVE1: TackleFast           MOVE2: FlameCharge          Candy: 59
[02:04:40] (INFO) # CP  715/ 759 | (63.89% perfect)     | Lvl 13         NAME: Seaking           MOVE1: PeckFast             MOVE2: IcyWind              Candy: 158
[02:04:40] (INFO) # CP  650/ 698 | (59.88% perfect)     | Lvl 13         NAME: Magneton          MOVE1: SparkFast            MOVE2: MagnetBomb           Candy: 118
[02:04:40] (INFO) # CP  614/ 742 | (8.77% perfect)      | Lvl 18         NAME: Raticate          MOVE1: BiteFast             MOVE2: Dig                  Candy: 14
[02:04:40] (INFO) # CP  607/ 651 | (65.18% perfect)     | Lvl 17         NAME: Poliwhirl         MOVE1: MudShotFast          MOVE2: Scald                Candy: 126
[02:04:40] (INFO) # CP  600/ 648 | (55.96% perfect)     | Lvl 12         NAME: Venomoth          MOVE1: ConfusionFast        MOVE2: Psychic              Candy: 42
[02:04:40] (INFO) # CP  592/ 682 | (10.87% perfect)     | Lvl 10         NAME: Golduck           MOVE1: WaterGunFast         MOVE2: IceBeam              Candy: 122
[02:04:40] (INFO) # CP  577/ 661 | (38.47% perfect)     | Lvl 19         NAME: Slowpoke          MOVE1: ConfusionFast        MOVE2: Psychic              Candy: 47
[02:04:41] (INFO) ====== DisplayHighestsPerfect ======
[02:04:41] (INFO) # CP  112/ 112 | (98.14% perfect)     | Lvl 04         NAME: Eevee             MOVE1: QuickAttackFast      MOVE2: Dig                  Candy: 47
[02:04:41] (INFO) # CP  284/ 288 | (94.18% perfect)     | Lvl 11         NAME: Jigglypuff        MOVE1: FeintAttackFast      MOVE2: PlayRough            Candy: 23
[02:04:41] (INFO) # CP  377/ 383 | (93.49% perfect)     | Lvl 16         NAME: Voltorb           MOVE1: SparkFast            MOVE2: SignalBeam           Candy: 148
[02:04:41] (INFO) # CP  111/ 113 | (92.82% perfect)     | Lvl 07         NAME: Rattata           MOVE1: QuickAttackFast      MOVE2: Dig                  Candy: 14
[02:04:41] (INFO) # CP  158/ 162 | (90.21% perfect)     | Lvl 06         NAME: Dratini           MOVE1: DragonBreathFast     MOVE2: Wrap                 Candy: 35
[02:04:41] (INFO) # CP  176/ 179 | (89.21% perfect)     | Lvl 04         NAME: Jynx              MOVE1: FrostBreathFast      MOVE2: DrainingKiss         Candy: 3
[02:04:41] (INFO) # CP  135/ 142 | (88.66% perfect)     | Lvl 19         NAME: Magikarp          MOVE1: SplashFast           MOVE2: Struggle             Candy: 375
[02:04:41] (INFO) # CP  451/ 468 | (84.17% perfect)     | Lvl 17         NAME: Goldeen           MOVE1: PeckFast             MOVE2: HornAttack           Candy: 158
[02:04:41] (INFO) # CP  431/ 447 | (82.86% perfect)     | Lvl 14         NAME: Omanyte           MOVE1: WaterGunFast         MOVE2: AncientPower         Candy: 7
[02:04:41] (INFO) # CP  752/ 779 | (81.44% perfect)     | Lvl 18         NAME: Ponyta            MOVE1: TackleFast           MOVE2: FlameCharge          Candy: 59
[02:04:42] (UPDATE) [Evolves] Potential Evolves: 0
[02:04:44] (INFO) Amount of Pokemon Seen: 89/151, Amount of Pokemon Caught: 88/151
[02:04:44] (INFO) Current Pokeballs: 50 | Greatballs: 117 | Ultraballs: 26 | Masterballs: 0
[02:04:44] (INFO) Current Total Potions: 30 | Total Revives: 30 | Berries: 80 | Total Incense: 4 | Lucky Eggs: 5 | Lures: 4
[02:04:45] (EGG) Incubator status update: 1.37km left
[02:04:45] (EGG) Incubator status update: 1.69km left
[02:04:45] (INFO) Traveling to Pokestop: Taman Bekapai (39m) (4 seconds)
[02:04:46] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by wetshrimp** [comment]
google broken for me

**Comment by xnikolai** [comment]
#2899 has the fix
