### ISSUE TITLE
JSON Exception on Login

### ISSUE THREAD

**Issue by heanforce** [NECROBOTIO/NecroBot#2914]
![capture](https://cloud.githubusercontent.com/assets/20890914/17464228/59e7c430-5cda-11e6-8488-61332fdf7d77.PNG)
I get this on login in on my remote machine.
Everything worked fine 10 minutes ago.
When I try login in on my local machine, everything works fine.

IP Bann? (Was running like 8 clients on my remote machine)

**Comment by saintwolf** [comment]
I'm getting the same after running 4 clients on my server for about 15min. Even after clearing the config I will get this error.

**Comment by hellnest** [comment]
IP Ban for sure. Try to re run this using VPN it worked again

**Comment by hellnest** [comment]
nope it broken again -_-

[02:04:38] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
[02:04:38] (INFO) Logging in using Google
[02:04:39] (INFO) Playing as UlunBogor
[02:04:39] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: -1.27660722764956 Lng: 116.834201603111
[02:04:40] (INFO) ====== DisplayHighestsCP ======
[02:04:40] (INFO) # CP 1094/1155 | (66.74% perfect)     | Lvl 20         NAME: Scyther           MOVE1: SteelWingFast        MOVE2: BugBuzz              Candy: 1
[02:04:40] (INFO) # CP  870/ 938 | (45.97% perfect)     | Lvl 11         NAME: Arcanine          MOVE1: BiteFast             MOVE2: Flamethrower         Candy: 33
[02:04:40] (INFO) # CP  752/ 779 | (81.44% perfect)     | Lvl 18         NAME: Ponyta            MOVE1: TackleFast           MOVE2: FlameCharge          Candy: 59
[02:04:40] (INFO) # CP  715/ 759 | (63.89% perfect)     | Lvl 13         NAME: Seaking           MOVE1: PeckFast             MOVE2: IcyWind              Candy: 158
[02:04:40] (INFO) # CP  650/ 698 | (59.88% perfect)     | Lvl 13         NAME: Magneton          MOVE1: SparkFast            MOVE2: MagnetBomb           Candy: 118
[02:04:40] (INFO) # CP  614/ 742 | (8.77% perfect)      | Lvl 18         NAME: Raticate          MOVE1: BiteFast             MOVE2: Dig                  Candy: 14
[02:04:40] (INFO) # CP  607/ 651 | (65.18% perfect)     | Lvl 17         NAME: Poliwhirl         MOVE1: MudShotFast          MOVE2: Scald                Candy: 126
[02:04:40] (INFO) # CP  600/ 648 | (55.96% perfect)     | Lvl 12         NAME: Venomoth          MOVE1: ConfusionFast        MOVE2: Psychic              Candy: 42
[02:04:40] (INFO) # CP  592/ 682 | (10.87% perfect)     | Lvl 10         NAME: Golduck           MOVE1: WaterGunFast         MOVE2: IceBeam              Candy: 122
[02:04:40] (INFO) # CP  577/ 661 | (38.47% perfect)     | Lvl 19         NAME: Slowpoke          MOVE1: ConfusionFast        MOVE2: Psychic              Candy: 47
[02:04:41] (INFO) ====== DisplayHighestsPerfect ======
[02:04:41] (INFO) # CP  112/ 112 | (98.14% perfect)     | Lvl 04         NAME: Eevee             MOVE1: QuickAttackFast      MOVE2: Dig                  Candy: 47
[02:04:41] (INFO) # CP  284/ 288 | (94.18% perfect)     | Lvl 11         NAME: Jigglypuff        MOVE1: FeintAttackFast      MOVE2: PlayRough            Candy: 23
[02:04:41] (INFO) # CP  377/ 383 | (93.49% perfect)     | Lvl 16         NAME: Voltorb           MOVE1: SparkFast            MOVE2: SignalBeam           Candy: 148
[02:04:41] (INFO) # CP  111/ 113 | (92.82% perfect)     | Lvl 07         NAME: Rattata           MOVE1: QuickAttackFast      MOVE2: Dig                  Candy: 14
[02:04:41] (INFO) # CP  158/ 162 | (90.21% perfect)     | Lvl 06         NAME: Dratini           MOVE1: DragonBreathFast     MOVE2: Wrap                 Candy: 35
[02:04:41] (INFO) # CP  176/ 179 | (89.21% perfect)     | Lvl 04         NAME: Jynx              MOVE1: FrostBreathFast      MOVE2: DrainingKiss         Candy: 3
[02:04:41] (INFO) # CP  135/ 142 | (88.66% perfect)     | Lvl 19         NAME: Magikarp          MOVE1: SplashFast           MOVE2: Struggle             Candy: 375
[02:04:41] (INFO) # CP  451/ 468 | (84.17% perfect)     | Lvl 17         NAME: Goldeen           MOVE1: PeckFast             MOVE2: HornAttack           Candy: 158
[02:04:41] (INFO) # CP  431/ 447 | (82.86% perfect)     | Lvl 14         NAME: Omanyte           MOVE1: WaterGunFast         MOVE2: AncientPower         Candy: 7
[02:04:41] (INFO) # CP  752/ 779 | (81.44% perfect)     | Lvl 18         NAME: Ponyta            MOVE1: TackleFast           MOVE2: FlameCharge          Candy: 59
[02:04:42] (UPDATE) [Evolves] Potential Evolves: 0
[02:04:44] (INFO) Amount of Pokemon Seen: 89/151, Amount of Pokemon Caught: 88/151
[02:04:44] (INFO) Current Pokeballs: 50 | Greatballs: 117 | Ultraballs: 26 | Masterballs: 0
[02:04:44] (INFO) Current Total Potions: 30 | Total Revives: 30 | Berries: 80 | Total Incense: 4 | Lucky Eggs: 5 | Lures: 4
[02:04:45] (EGG) Incubator status update: 1.37km left
[02:04:45] (EGG) Incubator status update: 1.69km left
[02:04:45] (INFO) Traveling to Pokestop: Taman Bekapai (39m) (4 seconds)
[02:04:46] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by Bam30** [comment]
got the exactly same problem.

**Comment by wetshrimp** [comment]
google is broken for necro

**Comment by saintwolf** [comment]
I'm using PTC and getting the same issue. Thought it was working again for a second but it just loops this exception and logs back in again constantly.

**Comment by heanforce** [comment]
Jep. Same here. PTC OR GOOGLE, it dont make a difference.

**Comment by joerigh** [comment]
0.7.0 with ptc still runing almost 5h, never had a problem... and crash when using google for 1h
now im using 0.7.2 for google and using auth and config file from 0.7.0

**Comment by TazDevil66** [comment]
![error](https://cloud.githubusercontent.com/assets/20891130/17464379/b811f900-5cd4-11e6-8706-871d9b86cedc.png)
I got this snapshot about 2 seconds after it errored. It had been running for about 4 mins before this happened.

**Comment by loqahkim** [comment]
Change your Ip address and it will works back online. If your ISP give you dynamic ip, just restart your router & modem.

**Comment by palmpje94** [comment]
necro is broken, i used 2 account so 1 i logged out to make some changes and after that i cannot log in, says it needs google loggin even though im using ptc for both and the other 1 worked until i did also stop that 1 to see if it had the same problem, and it does...

**Comment by proesd** [comment]
I have same issue as @TazDevil66 had, just continued it or re-run it..

**Comment by auth100488** [comment]
Here's what I've tried so far...
Keep config files / delete temps + lastpos.ini + log.
Still crashing.
Rebooted, still crashes.
Kept config files but replaced the original .exe and other files with the ones in the release.zip... still crash
used brand new files from release.zip in the same folder, deleted all other files, started the exe, it prompted if i wanted to go through with the config, i did, then restarted boom crash.

Used a free vpn just to test ... seems to be working...

**Comment by japstories** [comment]
so... ciamo is global IP address?

**Comment by joerigh** [comment]
![runandrun](https://cloud.githubusercontent.com/assets/7541965/17464421/68498436-5d08-11e6-9bb7-848e136f7fe5.jpg)

how long 0.7.2 with google.. just wait and see

**Comment by auth100488** [comment]
i wouldn't post the username in your screenshots ... just saying haha!

**Comment by joerigh** [comment]
lol that not my main acc... :dancers:

**Comment by FreeSampleThief** [comment]
Not softban or IP ban.  Verified with secondary account GPS spoof on mobile device while using same IP. Problem is with the bot.

**Comment by jodendaal** [comment]
Yes, it does appear to be the bot. I used my VPN and it then connected. I have another app I made that uses the Rocket API and it works fine without VPN.

**Comment by TazDevil66** [comment]
Just started pokemon Go up using NOX and all is well. Deffo a prob with the bot. Can run bot using VPN (Windscribe)and it works fine

**Comment by saintwolf** [comment]
I think it's a configuration issue. I used someone's config file from http://www.xup.in/dl,12267811/config.json/ and it works fine (Although I was soft-banned due to the coords).

When I tried this on a different instance of my bot, but changed the coords to my local(ish) ones; it did crashed with the usual error.

**Comment by heanforce** [comment]
Tryed out your config. Doesn't make a change for me :/ Strange

**Comment by saintwolf** [comment]
Update from me: it only works on 3/4 of my bots. The 4th one I have deleted all of the code and unzipped a fresh version of a bot with the config file. That one won't work at all

**Comment by heanforce** [comment]
It has may something to do with the coords?! For example I run 5 bots at the same coords at login (Suspect?!). Coords are changed to a far location due to the new config: Problem solved?

**Comment by auth100488** [comment]
all 3 died after 45 minutes 3 diff ips. deff not an ip related

**Comment by joerigh** [comment]
try to set `MaxTravelDistanceInMeters` to short distance. im using 600

**Comment by mkkilla** [comment]
@saintwolf i used the config all i keep getting are pidgeys and weedles but bot works how do i change that
