### ISSUE TITLE
 exceeded your daily request quota from maps.googleapis.com for elevation 

### ISSUE THREAD

**Issue by mrnitrate** [NECROBOTIO/NecroBot#2917]
[12:02:15] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\Nitrate\NecroBot-Mr\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 39

   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\Nitrate\NecroB
ot-Mr\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 67
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\Nitrate\NecroBot-Mr\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\Nitrate\NecroBot-Mr\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Nitrate\NecroBot-Mr\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Nitrate\NecroBot-Mr\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

And when you go to the maps urls directly, https://maps.googleapis.com/maps/api/elevation/json?locations={}
{
   "error_message" : "You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"
}

**Comment by mrnitrate** [comment]
was able to sign up for an api key at https://console.developers.google.com/apis/api/elevation_backend/overview

then had to change Utils\LocationUtils.cs::34  to  
var request = (HttpWebRequest)WebRequest.Create(string.Format("https://maps.googleapis.com/maps/api/elevation/json?locations={0},{1}&key={2}", point.Latitude, point.Longitude, "[YOUR_API_KEY]"));

**Comment by mrnitrate** [comment]
but even then you still only get 2500 free api calls a day with the key, https://developers.google.com/maps/documentation/geocoding/usage-limits

**Comment by gallantdon** [comment]
I am having the same problem, where you able to fix it with the API_KEY?

**Comment by centoxe** [comment]
I fixed mine with getting a new api key but this doesnt last very long i will just wait for the fix
