### ISSUE TITLE
Stapelüberwachung-Error

### ISSUE THREAD

**Issue by ntoday** [NECROBOTIO/NecroBot#2927]
Hey guys,
as soon as you boot up the .exe, this error message starts to appear, whenever the program wants to search for a new pokestop. If you got Pokemon it can evolve/transfer, it does that first. Any idea on how to fix it? (Using 0.7.2)

```
[20:26:14] (ERROR) System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: value
   bei Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   bei Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   bei PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:Zeile 36.
   bei PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:Zeile 65.
   bei PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:Zeile 42.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:Zeile 82.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:Zeile 66.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:Zeile 36.
```

**Comment by Bannz** [comment]
same..

**Comment by ryanpradhitya** [comment]
same problem here

**Comment by aherradorf** [comment]
same

**Comment by SacTurY** [comment]
same

**Comment by fidelitynina** [comment]
Bot works for a couple of hours fine. Now i have the same problem...

**Comment by kan22955500** [comment]
same problem

**Comment by richinl** [comment]
same

**Comment by richinl** [comment]
[02:49:38] Current Total Potions: 202 | Total Revives: 111 | Berries: 54 | Total Incense: 0 | Lucky Eggs: 4 | Lures: 9
[02:49:39] Incubator status update: 3.88km left
[02:49:40] Traveling to Pokestop: King Edward VII Statue (49m) (5 seconds)
[02:49:41] System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
