### ISSUE TITLE
Broken again :c

### ISSUE THREAD

**Issue by bennextmitchell** [NECROBOTIO/NecroBot#2964]
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.L
ogic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.
Logic\State\StateMachine.cs:line 36
[19:09:40] (INFO) Logging in using Google
[19:09:41] (INFO) Playing as Cameroono27
[19:09:41] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 35.6325724162108 Lng: 139.879997055591
[19:09:41] (INFO) ====== DisplayHighestsCP ======
[19:09:41] (INFO) # CP  959/1000 | (66.86% perfect)     | Lvl 10         NAME: Dragonite         MOVE1: DragonBreathFast
   MOVE2: HyperBeam            Candy: 16
[19:09:41] (INFO) # CP  571/ 635 | (30.95% perfect)     | Lvl 09         NAME: Nidoqueen         MOVE1: BiteFast
   MOVE2: SludgeWave           Candy: 18
[19:09:41] (INFO) # CP  543/ 581 | (53.65% perfect)     | Lvl 08         NAME: Venusaur          MOVE1: VineWhipFast
   MOVE2: SludgeBomb           Candy: 6
[19:09:41] (INFO) # CP  542/ 593 | (46.46% perfect)     | Lvl 10         NAME: Gengar            MOVE1: SuckerPunchFast
   MOVE2: DarkPulse            Candy: 10
[19:09:41] (INFO) # CP  510/ 573 | (24.47% perfect)     | Lvl 08         NAME: Blastoise         MOVE1: BiteFast
   MOVE2: HydroPump            Candy: 10
[19:09:41] (INFO) # CP  480/ 516 | (52.86% perfect)     | Lvl 07         NAME: Flareon           MOVE1: EmberFast
   MOVE2: FireBlast            Candy: 18
[19:09:41] (INFO) # CP  470/ 487 | (73.75% perfect)     | Lvl 06         NAME: Exeggutor         MOVE1: ConfusionFast
   MOVE2: Psychic              Candy: 6
[19:09:41] (INFO) # CP  455/ 482 | (63.97% perfect)     | Lvl 08         NAME: Jolteon           MOVE1: ThunderShockFast
   MOVE2: Discharge            Candy: 18
[19:09:41] (INFO) # CP  452/ 482 | (61.13% perfect)     | Lvl 08         NAME: Jolteon           MOVE1: ThunderShockFast
   MOVE2: Thunderbolt          Candy: 18
[19:09:41] (INFO) # CP  397/ 428 | (48.88% perfect)     | Lvl 06         NAME: Slowbro           MOVE1: WaterGunFast
   MOVE2: Psychic              Candy: 18
[19:09:42] (INFO) ====== DisplayHighestsPerfect ======
[19:09:42] (INFO) # CP  203/ 204 | (97.69% perfect)     | Lvl 05         NAME: Hitmonchan        MOVE1: RockSmashFast
   MOVE2: BrickBreak           Candy: 39
[19:09:42] (INFO) # CP   11/  11 | (92.35% perfect)     | Lvl 01         NAME: Gastly            MOVE1: LickFast
   MOVE2: OminousWind          Candy: 10
[19:09:42] (INFO) # CP   34/  35 | (91.69% perfect)     | Lvl 02         NAME: Krabby            MOVE1: MudShotFast
   MOVE2: BubbleBeam           Candy: 39
[19:09:42] (INFO) # CP  294/ 303 | (86.73% perfect)     | Lvl 11         NAME: Goldeen           MOVE1: MudShotFast
   MOVE2: HornAttack           Candy: 47
[19:09:42] (INFO) # CP   63/  67 | (86.21% perfect)     | Lvl 09         NAME: Magikarp          MOVE1: SplashFast
   MOVE2: Struggle             Candy: 30
[19:09:42] (INFO) # CP  117/ 122 | (83.50% perfect)     | Lvl 04         NAME: Dugtrio           MOVE1: SuckerPunchFast
   MOVE2: Earthquake           Candy: 6
[19:09:42] (INFO) # CP  212/ 221 | (82.09% perfect)     | Lvl 08         NAME: Dratini           MOVE1: DragonBreathFast
   MOVE2: Wrap                 Candy: 16
[19:09:42] (INFO) # CP  216/ 222 | (80.93% perfect)     | Lvl 03         NAME: Arcanine          MOVE1: FireFangFast
   MOVE2: FireBlast            Candy: 9
[19:09:42] (INFO) # CP   10/  10 | (80.09% perfect)     | Lvl 01         NAME: Rattata           MOVE1: QuickAttackFast
   MOVE2: BodySlam             Candy: 62
[19:09:42] (INFO) # CP  173/ 183 | (78.58% perfect)     | Lvl 07         NAME: Staryu            MOVE1: QuickAttackFast
   MOVE2: Swift                Candy: 23
[19:09:42] (UPDATE) [Evolves] Potential Evolves: 8
[19:09:42] (INFO) Waiting to evolve 8 Pokemon once 140 more are caught! (85/225 for 90% inventory)
[19:09:43] (INFO) Amount of Pokemon Seen: 78/151, Amount of Pokemon Caught: 76/151
[19:09:43] (INFO) Current Pokeballs: 233 | Greatballs: 17 | Ultraballs: 0 | Masterballs: 0
[19:09:43] (INFO) Current Total Potions: 1 | Total Revives: 1 | Berries: 50 | Total Incense: 5 | Lucky Eggs: 2 | Lures: 2
[19:09:43] (EGG) Incubator status update: 3.21km left
[19:09:43] (EGG) Incubator status update: 3.60km left
[19:09:43] (EGG) Incubator status update: 3.92km left
[19:09:44] (INFO) Traveling to Pokestop: Castle Tower (35m) (0 seconds)
[19:09:44] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot
\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double
 bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Nav
igation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.Ne
croBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.L
ogic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.
Logic\State\StateMachine.cs:line 36
[19:09:44] (INFO) Logging in using Google
[19:09:45] (INFO) Playing as Cameroono27
[19:09:45] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 35.6325724162108 Lng: 139.879997055591
[19:09:45] (INFO) ====== DisplayHighestsCP ======
[19:09:45] (INFO) # CP  959/1000 | (66.86% perfect)     | Lvl 10         NAME: Dragonite         MOVE1: DragonBreathFast
   MOVE2: HyperBeam            Candy: 16
[19:09:45] (INFO) # CP  571/ 635 | (30.95% perfect)     | Lvl 09         NAME: Nidoqueen         MOVE1: BiteFast
   MOVE2: SludgeWave           Candy: 18
[19:09:45] (INFO) # CP  543/ 581 | (53.65% perfect)     | Lvl 08         NAME: Venusaur          MOVE1: VineWhipFast
   MOVE2: SludgeBomb           Candy: 6
[19:09:45] (INFO) # CP  542/ 593 | (46.46% perfect)     | Lvl 10         NAME: Gengar            MOVE1: SuckerPunchFast
   MOVE2: DarkPulse            Candy: 10
[19:09:45] (INFO) # CP  510/ 573 | (24.47% perfect)     | Lvl 08         NAME: Blastoise         MOVE1: BiteFast
   MOVE2: HydroPump            Candy: 10
[19:09:45] (INFO) # CP  480/ 516 | (52.86% perfect)     | Lvl 07         NAME: Flareon           MOVE1: EmberFast
   MOVE2: FireBlast            Candy: 18
[19:09:45] (INFO) # CP  470/ 487 | (73.75% perfect)     | Lvl 06         NAME: Exeggutor         MOVE1: ConfusionFast
   MOVE2: Psychic              Candy: 6
[19:09:45] (INFO) # CP  455/ 482 | (63.97% perfect)     | Lvl 08         NAME: Jolteon           MOVE1: ThunderShockFast
   MOVE2: Discharge            Candy: 18
[19:09:45] (INFO) # CP  452/ 482 | (61.13% perfect)     | Lvl 08         NAME: Jolteon           MOVE1: ThunderShockFast
   MOVE2: Thunderbolt          Candy: 18
[19:09:45] (INFO) # CP  397/ 428 | (48.88% perfect)     | Lvl 06         NAME: Slowbro           MOVE1: WaterGunFast
   MOVE2: Psychic              Candy: 18
[19:09:46] (INFO) ====== DisplayHighestsPerfect ======
[19:09:46] (INFO) # CP  203/ 204 | (97.69% perfect)     | Lvl 05         NAME: Hitmonchan        MOVE1: RockSmashFast
   MOVE2: BrickBreak           Candy: 39
[19:09:46] (INFO) # CP   11/  11 | (92.35% perfect)     | Lvl 01         NAME: Gastly            MOVE1: LickFast
   MOVE2: OminousWind          Candy: 10
[19:09:46] (INFO) # CP   34/  35 | (91.69% perfect)     | Lvl 02         NAME: Krabby            MOVE1: MudShotFast
   MOVE2: BubbleBeam           Candy: 39
[19:09:46] (INFO) # CP  294/ 303 | (86.73% perfect)     | Lvl 11         NAME: Goldeen           MOVE1: MudShotFast
   MOVE2: HornAttack           Candy: 47
[19:09:46] (INFO) # CP   63/  67 | (86.21% perfect)     | Lvl 09         NAME: Magikarp          MOVE1: SplashFast
   MOVE2: Struggle             Candy: 30
[19:09:46] (INFO) # CP  117/ 122 | (83.50% perfect)     | Lvl 04         NAME: Dugtrio           MOVE1: SuckerPunchFast
   MOVE2: Earthquake           Candy: 6
[19:09:46] (INFO) # CP  212/ 221 | (82.09% perfect)     | Lvl 08         NAME: Dratini           MOVE1: DragonBreathFast
   MOVE2: Wrap                 Candy: 16
[19:09:46] (INFO) # CP  216/ 222 | (80.93% perfect)     | Lvl 03         NAME: Arcanine          MOVE1: FireFangFast
   MOVE2: FireBlast            Candy: 9
[19:09:46] (INFO) # CP   10/  10 | (80.09% perfect)     | Lvl 01         NAME: Rattata           MOVE1: QuickAttackFast
   MOVE2: BodySlam             Candy: 62
[19:09:46] (INFO) # CP  173/ 183 | (78.58% perfect)     | Lvl 07         NAME: Staryu            MOVE1: QuickAttackFast
   MOVE2: Swift                Candy: 23
[19:09:47] (UPDATE) [Evolves] Potential Evolves: 8
[19:09:47] (INFO) Waiting to evolve 8 Pokemon once 140 more are caught! (85/225 for 90% inventory)
[19:09:47] (INFO) Amount of Pokemon Seen: 78/151, Amount of Pokemon Caught: 76/151
[19:09:47] (INFO) Current Pokeballs: 233 | Greatballs: 17 | Ultraballs: 0 | Masterballs: 0
[19:09:47] (INFO) Current Total Potions: 1 | Total Revives: 1 | Berries: 50 | Total Incense: 5 | Lucky Eggs: 2 | Lures: 2
[19:09:47] (EGG) Incubator status update: 3.21km left
[19:09:47] (EGG) Incubator status update: 3.60km left
[19:09:47] (EGG) Incubator status update: 3.92km left
[19:09:48] (INFO) Traveling to Pokestop: Castle Tower (35m) (0 seconds)
[19:09:48] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot
\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double
 bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Nav
igation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.Ne
croBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.L
ogic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.
Logic\State\StateMachine.cs:line 36
[19:09:48] (INFO) Logging in using Google
[19:09:49] (INFO) Playing as Cameroono27
[19:09:49] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 35.6325724162108 Lng: 139.879997055591
[19:09:50] (INFO) ====== DisplayHighestsCP ======
[19:09:50] (INFO) # CP  959/1000 | (66.86% perfect)     | Lvl 10         NAME: Dragonite         MOVE1: DragonBreathFast
   MOVE2: HyperBeam            Candy: 16
[19:09:50] (INFO) # CP  571/ 635 | (30.95% perfect)     | Lvl 09         NAME: Nidoqueen         MOVE1: BiteFast
   MOVE2: SludgeWave           Candy: 18
[19:09:50] (INFO) # CP  543/ 581 | (53.65% perfect)     | Lvl 08         NAME: Venusaur          MOVE1: VineWhipFast
   MOVE2: SludgeBomb           Candy: 6
[19:09:50] (INFO) # CP  542/ 593 | (46.46% perfect)     | Lvl 10         NAME: Gengar            MOVE1: SuckerPunchFast
   MOVE2: DarkPulse            Candy: 10
[19:09:50] (INFO) # CP  510/ 573 | (24.47% perfect)     | Lvl 08         NAME: Blastoise         MOVE1: BiteFast
   MOVE2: HydroPump            Candy: 10
[19:09:50] (INFO) # CP  480/ 516 | (52.86% perfect)     | Lvl 07         NAME: Flareon           MOVE1: EmberFast
   MOVE2: FireBlast            Candy: 18
[19:09:50] (INFO) # CP  470/ 487 | (73.75% perfect)     | Lvl 06         NAME: Exeggutor         MOVE1: ConfusionFast
   MOVE2: Psychic              Candy: 6
[19:09:50] (INFO) # CP  455/ 482 | (63.97% perfect)     | Lvl 08         NAME: Jolteon           MOVE1: ThunderShockFast
   MOVE2: Discharge            Candy: 18
[19:09:50] (INFO) # CP  452/ 482 | (61.13% perfect)     | Lvl 08         NAME: Jolteon           MOVE1: ThunderShockFast
   MOVE2: Thunderbolt          Candy: 18
[19:09:50] (INFO) # CP  397/ 428 | (48.88% perfect)     | Lvl 06         NAME: Slowbro           MOVE1: WaterGunFast
   MOVE2: Psychic              Candy: 18
[19:09:50] (INFO) ====== DisplayHighestsPerfect ======
[19:09:50] (INFO) # CP  203/ 204 | (97.69% perfect)     | Lvl 05         NAME: Hitmonchan        MOVE1: RockSmashFast
   MOVE2: BrickBreak           Candy: 39
[19:09:50] (INFO) # CP   11/  11 | (92.35% perfect)     | Lvl 01         NAME: Gastly            MOVE1: LickFast
   MOVE2: OminousWind          Candy: 10
[19:09:50] (INFO) # CP   34/  35 | (91.69% perfect)     | Lvl 02         NAME: Krabby            MOVE1: MudShotFast
   MOVE2: BubbleBeam           Candy: 39
[19:09:50] (INFO) # CP  294/ 303 | (86.73% perfect)     | Lvl 11         NAME: Goldeen           MOVE1: MudShotFast
   MOVE2: HornAttack           Candy: 47
[19:09:50] (INFO) # CP   63/  67 | (86.21% perfect)     | Lvl 09         NAME: Magikarp          MOVE1: SplashFast
   MOVE2: Struggle             Candy: 30
[19:09:50] (INFO) # CP  117/ 122 | (83.50% perfect)     | Lvl 04         NAME: Dugtrio           MOVE1: SuckerPunchFast
   MOVE2: Earthquake           Candy: 6
[19:09:50] (INFO) # CP  212/ 221 | (82.09% perfect)     | Lvl 08         NAME: Dratini           MOVE1: DragonBreathFast
   MOVE2: Wrap                 Candy: 16
[19:09:50] (INFO) # CP  216/ 222 | (80.93% perfect)     | Lvl 03         NAME: Arcanine          MOVE1: FireFangFast
   MOVE2: FireBlast            Candy: 9
[19:09:50] (INFO) # CP   10/  10 | (80.09% perfect)     | Lvl 01         NAME: Rattata           MOVE1: QuickAttackFast
   MOVE2: BodySlam             Candy: 62
[19:09:50] (INFO) # CP  173/ 183 | (78.58% perfect)     | Lvl 07         NAME: Staryu            MOVE1: QuickAttackFast
   MOVE2: Swift                Candy: 23
[19:09:51] (UPDATE) [Evolves] Potential Evolves: 8
[19:09:51] (INFO) Waiting to evolve 8 Pokemon once 140 more are caught! (85/225 for 90% inventory)
[19:09:52] (INFO) Amount of Pokemon Seen: 78/151, Amount of Pokemon Caught: 76/151
[19:09:52] (INFO) Current Pokeballs: 233 | Greatballs: 17 | Ultraballs: 0 | Masterballs: 0
[19:09:52] (INFO) Current Total Potions: 1 | Total Revives: 1 | Berries: 50 | Total Incense: 5 | Lucky Eggs: 2 | Lures: 2
[19:09:52] (EGG) Incubator status update: 3.21km left
[19:09:52] (EGG) Incubator status update: 3.60km left
[19:09:52] (EGG) Incubator status update: 3.92km left
[19:09:53] (INFO) Traveling to Pokestop: Castle Tower (35m) (0 seconds)
[19:09:53] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot
\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double
 bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Nav
igation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.Ne
croBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.L
ogic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.
Logic\State\StateMachine.cs:line 36
[19:09:53] (INFO) Logging in using Google
[19:09:54] (INFO) Playing as Cameroono27
[19:09:54] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 35.6325724162108 Lng: 139.879997055591
[19:09:54] (INFO) ====== DisplayHighestsCP ======
[19:09:54] (INFO) # CP  959/1000 | (66.86% perfect)     | Lvl 10         NAME: Dragonite         MOVE1: DragonBreathFast
   MOVE2: HyperBeam            Candy: 16
[19:09:54] (INFO) # CP  571/ 635 | (30.95% perfect)     | Lvl 09         NAME: Nidoqueen         MOVE1: BiteFast
   MOVE2: SludgeWave           Candy: 18
[19:09:54] (INFO) # CP  543/ 581 | (53.65% perfect)     | Lvl 08         NAME: Venusaur          MOVE1: VineWhipFast
   MOVE2: SludgeBomb           Candy: 6
[19:09:54] (INFO) # CP  542/ 593 | (46.46% perfect)     | Lvl 10         NAME: Gengar            MOVE1: SuckerPunchFast
   MOVE2: DarkPulse            Candy: 10
[19:09:54] (INFO) # CP  510/ 573 | (24.47% perfect)     | Lvl 08         NAME: Blastoise         MOVE1: BiteFast
   MOVE2: HydroPump            Candy: 10
[19:09:54] (INFO) # CP  480/ 516 | (52.86% perfect)     | Lvl 07         NAME: Flareon           MOVE1: EmberFast
   MOVE2: FireBlast            Candy: 18
[19:09:54] (INFO) # CP  470/ 487 | (73.75% perfect)     | Lvl 06         NAME: Exeggutor         MOVE1: ConfusionFast
   MOVE2: Psychic              Candy: 6
[19:09:54] (INFO) # CP  455/ 482 | (63.97% perfect)     | Lvl 08         NAME: Jolteon           MOVE1: ThunderShockFast
   MOVE2: Discharge            Candy: 18
[19:09:54] (INFO) # CP  452/ 482 | (61.13% perfect)     | Lvl 08         NAME: Jolteon           MOVE1: ThunderShockFast
   MOVE2: Thunderbolt          Candy: 18
[19:09:54] (INFO) # CP  397/ 428 | (48.88% perfect)     | Lvl 06         NAME: Slowbro           MOVE1: WaterGunFast
   MOVE2: Psychic              Candy: 18
[19:09:54] (INFO) ====== DisplayHighestsPerfect ======
[19:09:54] (INFO) # CP  203/ 204 | (97.69% perfect)     | Lvl 05         NAME: Hitmonchan        MOVE1: RockSmashFast
   MOVE2: BrickBreak           Candy: 39
[19:09:54] (INFO) # CP   11/  11 | (92.35% perfect)     | Lvl 01         NAME: Gastly            MOVE1: LickFast
   MOVE2: OminousWind          Candy: 10
[19:09:54] (INFO) # CP   34/  35 | (91.69% perfect)     | Lvl 02         NAME: Krabby            MOVE1: MudShotFast
   MOVE2: BubbleBeam           Candy: 39
[19:09:54] (INFO) # CP  294/ 303 | (86.73% perfect)     | Lvl 11         NAME: Goldeen           MOVE1: MudShotFast
   MOVE2: HornAttack           Candy: 47
[19:09:54] (INFO) # CP   63/  67 | (86.21% perfect)     | Lvl 09         NAME: Magikarp          MOVE1: SplashFast
   MOVE2: Struggle             Candy: 30
[19:09:54] (INFO) # CP  117/ 122 | (83.50% perfect)     | Lvl 04         NAME: Dugtrio           MOVE1: SuckerPunchFast
   MOVE2: Earthquake           Candy: 6
[19:09:54] (INFO) # CP  212/ 221 | (82.09% perfect)     | Lvl 08         NAME: Dratini           MOVE1: DragonBreathFast
   MOVE2: Wrap                 Candy: 16
[19:09:54] (INFO) # CP  216/ 222 | (80.93% perfect)     | Lvl 03         NAME: Arcanine          MOVE1: FireFangFast
   MOVE2: FireBlast            Candy: 9
[19:09:54] (INFO) # CP   10/  10 | (80.09% perfect)     | Lvl 01         NAME: Rattata           MOVE1: QuickAttackFast
   MOVE2: BodySlam             Candy: 62
[19:09:54] (INFO) # CP  173/ 183 | (78.58% perfect)     | Lvl 07         NAME: Staryu            MOVE1: QuickAttackFast
   MOVE2: Swift                Candy: 23

**Comment by kompressor96** [comment]
use version 0.7.0 and set autoupdate false in the config file

**Comment by Caliboss** [comment]
[12:10:02] Exceptiion caught, writing LogBuffer. , wont even let me login

**Comment by advancedz** [comment]
is it 0.71 working?

**Comment by kompressor96** [comment]
yeah

**Comment by eBitzu** [comment]
I won't go back to old settings cuz that will be bad for mobile info sent

**Comment by archonis83** [comment]
https://github.com/NECROBOTIO/NecroBot/releases
