### ISSUE TITLE
Exception Caught, writing LogBuffer. Not sure how to fix this

### ISSUE THREAD

**Issue by damalujordan** [NECROBOTIO/NecroBot#2974]
I'm getting this error whenever I try to run NecroBot. Does anyone know how to resolve this?

![image](https://cloud.githubusercontent.com/assets/20890422/17464669/85b0659a-5cb2-11e6-8d8c-f1984b17a826.png)

**Comment by PewSztiePoll** [comment]
same here

**Comment by darklinki** [comment]
got the same error

**Comment by Cyrus-Wong** [comment]
same here

**Comment by N3KRoN** [comment]
same here...

**Comment by BlareKid** [comment]
same

**Comment by tomassymonds** [comment]
Yeah me too

**Comment by vcafezinho** [comment]
I guess I have the same:

[14:21:12] (ERROR) System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in D:\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 39
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in D:\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 67
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in D:\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in D:\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in D:\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in D:\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by Junkz1337** [comment]
same for me iam sure he will fix it.

[21:20:22] () Exceptiion caught, writing LogBuffer.

Unbehandelte Ausnahme: System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: value
   bei Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   bei Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   bei PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:Zeile 36.
   bei PoGo.NecroBot.Logic.ClientSettings.PokemonGo.RocketAPI.ISettings.get_DefaultAltitude() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Settings.cs:Zeile 1095.
   bei PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy apiFailureStrategy) in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Client.cs:Zeile 60.
   bei PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:Zeile 53.
   bei PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:Zeile 32.
   bei PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.CLI\Program.cs:Zeile 77.

**Comment by PewSztiePoll** [comment]
@vcafezinho  your error is seemed to be like [#2974](https://github.com/NECROBOTIO/NecroBot/issues/2974). Download 0.7.0 version of the bot.

**Comment by rozzis** [comment]
download 0.7.0 and set autoupdate false in config.

**Comment by tomassymonds** [comment]
Where is 0.7.0?

**Comment by Junkz1337** [comment]
iam sure he will fix it the bot workt great :palm_tree:

**Comment by vcafezinho** [comment]
@PewSztiePoll and @rozzis I already have the last version.

**Comment by Cyrus-Wong** [comment]
https://github.com/NECROBOTIO/NecroBot/releases/tag/v0.7.0

but while file to set the autoupdate to false?

**Comment by PewSztiePoll** [comment]
@vcafezinho not 0.7.2 which is the latest for now. Use previous version of the bot using link in the comment above

**Comment by PewSztiePoll** [comment]
@Cyrus-Wong config.json

**Comment by vcafezinho** [comment]
@PewSztiePoll Yeah got it thanks man

**Comment by Jordano3710** [comment]
@PewSztiePoll Thanks for telling me to download 0.7.0 works great mate thanks! :)

**Comment by Junkz1337** [comment]
0.7.2 works :)

**Comment by darklinki** [comment]
got 0.7.2 same error

**Comment by Jordano3710** [comment]
@darklinki Use Version 0.7.0 and it shall work fine

**Comment by Cyrus-Wong** [comment]
I'm getting "possible softban", anyone?

**Comment by Jordano3710** [comment]
@Cyrus-Wong Just Reload the bot
