### ISSUE TITLE
[ERROR] ArgumentNullException: Value cannot be null [HELP]

### ISSUE THREAD

**Issue by soulbeaster** [NECROBOTIO/NecroBot#2994]
![image](https://cloud.githubusercontent.com/assets/20718422/17464841/5bddbab4-5d12-11e6-916c-7a4f8f4560b5.png)

Anyone can help me ?

[UPDATE]
1) [VERIFIED] Downgrade your bot to ver 0.7.1 WORK PERFECTLY, just backup your AUTH and CONFIG
2) [VERIFIED] Just copy your NecroBot.exe ( Application ) from 0.7.1 version to 0.7.2 version

Dont forget TURN OFF AUTO UPDATE when you using old version

**Comment by JeremyVriens** [comment]
Same issue here.

**Comment by panacuba** [comment]
Already reported in a different issue. Im also experiencing this same problem.

**Comment by soulbeaster** [comment]
I think just me got this issue :( 
Okay this must be global issue

**Comment by Caliboss** [comment]
yes i had it, and wouldnt go away. download version 0.7.0 and it goes away. turn auto update off

**Comment by darklinki** [comment]
Yeah but dont go back to 0.7 if you dont want to risk a ban. There is no device informations in 0.7

**Comment by nikhiljha** [comment]
I have this as well, here's the text version of it:

[12:50:06] System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by panacuba** [comment]
can some one confirm if 0.7.1 can be used as a workarround for this?

**Comment by Caliboss** [comment]
if its bannable wouldnt they take the link down? it would have never been released if bannable.. right?

**Comment by darklinki** [comment]
actually niantic doesnt ban someone, but they could look in the request and ban you any time later. Better dont risk it and wait for a new release

**Comment by centoxe** [comment]
just use 0.7.1 works 
https://github.com/NECROBOTIO/NecroBot/releases

**Comment by GitClucked** [comment]
Agreed with centoxe. Changed out to 0.7.1 and its working perfectly.

**Comment by soulbeaster** [comment]
[VERIFIED] 0.7.1 WORK PERFECTLY, just backup your AUTH and CONFIG

**Comment by soulbeaster** [comment]
Have another option :

Just copy your NecroBot.exe ( Application ) from 0.7.1 version to 0.7.2 version

That resolve our problem too :)

**Comment by darklinki** [comment]
Cant get 0.7.1 working, every time "Fill out auth.json"

Even if its filled out

**Comment by JABirchall** [comment]
And disable Auto-update!

also, the issue was invoked by this commit! https://github.com/NECROBOTIO/NecroBot/commit/a345cff212820fc5421b91dd69996f3d70eccac8

**Comment by Sylencer90** [comment]
Hoping for 0.7.3 to release fast :D

**Comment by soulbeaster** [comment]
Yeah dont forget TURN OFF AUTO UPDATE when you using old version

**Comment by jasonkimberson** [comment]
The commit was correct, the public calls to the elevation api on google maxed out.  You can fix this by getting an API key and appending it to the maps call in visual studio and recompiling  

_________________________________

And disable Auto-update!

also, the issue was invoked by this commit! a345cff

**Comment by zybertronix** [comment]
is it still safe to use 7.0?
