### ISSUE TITLE
 [ERROR] Issue loading translations

### ISSUE THREAD

**Issue by Superbigboss** [NECROBOTIO/NecroBot#2998]
[01:23:44] System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 36
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CreateWaypoint(GeoCoordinate sourceLocation, Double distanceInMeters, Double bearingDegrees) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 65
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
[01:23:44] Logging in using Google

**Comment by Superbigboss** [comment]
![image](https://cloud.githubusercontent.com/assets/20891911/17464906/8df6fc44-5d13-11e6-906c-78f21dd49120.png)

**Comment by Superbigboss** [comment]
![image](https://cloud.githubusercontent.com/assets/20891911/17464911/a75d99ea-5d13-11e6-818c-57adc56cac13.png)

**Comment by daneil1999123** [comment]
same

**Comment by VXT108** [comment]
same

**Comment by csong5** [comment]
same

**Comment by Superbigboss** [comment]
![image](https://cloud.githubusercontent.com/assets/20891911/17464948/48c8c2c8-5d14-11e6-99c8-6d1f6a404056.png)

**Comment by gigi944** [comment]
same here, italian translation

**Comment by SklyC** [comment]
use v0.7.1

v0.7.1 has not this Issue

**Comment by rafaelsaru** [comment]
same here

**Comment by panacuba** [comment]
as @SklyC said, downgrade to version 0.7.1

**Comment by KuuuroNeko** [comment]
How can i downgrade to 0.7.1 version?

**Comment by davidmac6** [comment]
https://github.com/NECROBOTIO/NecroBot/releases using this link and scroll down till you see older version

**Comment by 11shwern** [comment]
I release the zip to v 0.7.1 then I change the autoupdate in configuration to false, but it still says I have v 0.7.2. Can someone tell me what I am doing wrong?

**Comment by shetonaz** [comment]
I can't even login with 0.7.1 version? Any suggestions?

**Comment by 11shwern** [comment]
Shetonaz, make sure when you run the application you "run as administrator"

**Comment by Superbigboss** [comment]
Thank
You can downgrade to 0.7.1 version
Downlond 0.7.1 (Open Folder Release/Config/config (JSON File Openwith Note)

"AutoUpdate": false,   Not True   

![image](https://cloud.githubusercontent.com/assets/20891911/17465061/16f33e9c-5d17-11e6-8906-972487adacf1.png)

**Comment by shetonaz** [comment]
@11shwern thank you, that helped :)

**Comment by 11shwern** [comment]
No problem man! Happy botting!

**Comment by soulbeaster** [comment]
#2994

**Comment by zybertronix** [comment]
is it still safe to use 7.0 ? i left the bot running on my server in the office lol!
