### ISSUE TITLE
LogBuffer

### ISSUE THREAD

**Issue by AIS94** [NECROBOTIO/NecroBot#3068]
Hi guys.. After I reopened the bot i get this error who stops def the bot:
"[00:20:40] () Exceptiion caught, writing LogBuffer.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at PoGo.NecroBot.Logic.Utils.LocationUtils.getElevation(Double lat, Double lon) in C:\NECROBOT\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 39
   at PoGo.NecroBot.Logic.ClientSettings.PokemonGo.RocketAPI.ISettings.get_DefaultAltitude() in C:\NECROBOT\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 1095
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy apiFailureStrategy) in C:\NECROBOT\NecroBot\FeroxRev\PokemonGo.RocketAPI\Client.cs:line 60
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings logicSettings) in C:\NECROBOT\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:line 54
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings logicSettings) in C:\NECROBOT\NecroBot\PoGo.NecroBot.Logic\State\Session.cs:line 33
   at PoGo.NecroBot.CLI.Program.Main(String[] args) in C:\NECROBOT\NecroBot\PoGo.NecroBot.CLI\Program.cs:line 77
Press any key to continue . . ."

**Comment by Aboukaied** [comment]
update to newest version 0.7.3 it has the fix

**Comment by AIS94** [comment]
@Aboukaied thanks a lot :D i have a question, if u don't mind.. it's better to pull the repository or let it auto-update ?
