### ISSUE TITLE
System.NullRefferenceException

### ISSUE THREAD

**Issue by Suny2589** [NECROBOTIO/NecroBot#3149]
```
02:14:02] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.PoGoUtils.PokemonInfo.GetCandy(PokemonData pokemon, List`1 PokemonFamilies, IEnumerable`1 PokemonSettings) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\PoGoUtils\PokemonInfo.cs:line 589
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<>c__DisplayClass2_0.<Execute>b__0(PokemonData pokemon) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 33
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
```
It seems it goes down again xD

**Comment by lucabravi** [comment]
same for me

**Comment by saahilz** [comment]
i am having the same issue on my google accounts
[00:18:03] Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7820802823572 Lng: -73.9668111814494
[00:18:04] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 354
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
[00:18:04] Logging in using Google
[00:18:05] Playing as Saahilz1
[00:18:05] Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7820802823572 Lng: -73.9668111814494
[00:18:05] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 354
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by zybertronix** [comment]
yes same here :(

**Comment by JameesJameesJamees** [comment]
Having 4 accounts working fine - only the 5th get this error, idk how to solve it.

**Comment by snyy** [comment]
im getting the same error

**Comment by OTTORE** [comment]
getting the same. Was using 7.1 fine, tried 7.5 and this error was given. Logging in back on 7.1 is giving same error. Other accounts are fine

**Comment by zybertronix** [comment]
same here 2 accounts on google works fine, its just the ptc account ... running on 7.5

**Comment by Ass3sin** [comment]
Same here...

**Comment by saahilz** [comment]
seems like the servers are having issues , must be all the bots crashing the damn servers LOL

**Comment by marburger93** [comment]
servers are currently offline
https://pokemongostatus.org/

**Comment by zybertronix** [comment]
downgraded my ptc account to 7.3.. google account running on 7.5 still. 
could it be a server ?
