### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by justme90** [NECROBOTIO/NecroBot#3158]
I keep getting this error message anyone know how to fix it?

(ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by SpykeReload** [comment]
Same here

**Comment by Onafets26** [comment]
Same here

**Comment by Sanskritmp** [comment]
#3152 
Read other issues so as to avoid spamming the section.
Requesting to close the issue.

**Comment by SpykeReload** [comment]
Servers are down

**Comment by M3NTI0N** [comment]
i bet niantic is updating theyr api again ;)

**Comment by saahilz** [comment]
no dont think they can do it this quickly this time, it will take them at least 1 or 2 weeks they firgure it out

**Comment by egsix** [comment]
Delete the auth.json file and run again the necrobot.exe to remake one auth.json file. Type your account and I think it will work.
