### ISSUE TITLE
Handle errors better when API is slow/laggy/unresponsive

### ISSUE THREAD

**Issue by dansali** [NECROBOTIO/NecroBot#3295]
> [04:29:37] Logging in using Google
> [04:29:39] System.NullReferenceException: Object reference not set to an instance of an object.
>    at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 135
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
> [04:29:39] Logging in using Google
> [04:29:41] System.NullReferenceException: Object reference not set to an instance of an object.
>    at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 135
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
> [04:29:41] Logging in using Google
> [04:29:42] System.NullReferenceException: Object reference not set to an instance of an object.
>    at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 135
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
> [04:29:42] Logging in using Google
> [04:29:44] System.NullReferenceException: Object reference not set to an instance of an object.
>    at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 135
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
> [04:29:44] Logging in using Google
> [04:29:46] Playing as 
> [04:29:46] Make sure Lat & Lng are right. Exit Program if not! Lat: -37.8100692895054 Lng: 144.965122114927
> [04:29:46] ====== DisplayHighestsCP ======
> 
> [04:29:47] ====== DisplayHighestsPerfect ======
> 
> [04:29:48] System.NullReferenceException: Object reference not set to an instance of an object.
>    at PoGo.NecroBot.Logic.Inventory.<>c__DisplayClass31_2.<GetPokemonToEvolve>b__5(Candy x) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 472
>    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at PoGo.NecroBot.Logic.Inventory.<GetPokemonToEvolve>d__31.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 472
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PoGo.NecroBot.Logic.Tasks.EvolvePokemonTask.<Execute>d__1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\EvolvePokemonTask.cs:line 27
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 18
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
> [04:29:48] Logging in using Google
> [04:29:49] System.NullReferenceException: Object reference not set to an instance of an object.
>    at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 135
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
>

**Comment by GitClucked** [comment]
Following. Same issue

**Comment by LIMBO199** [comment]
i got same situation

**Comment by iCreatZ** [comment]
same

**Comment by Isfan14** [comment]
same heree

**Comment by KuroHunter13** [comment]
same issue. please fix it

**Comment by hammerhead13** [comment]
Same Here! :(

**Comment by ChemiHatake** [comment]
the servers are down

**Comment by marburger93** [comment]
https://pokemongostatus.org/
Server Status: Offline

**Comment by Bunchhieng** [comment]
Server is currently down. https://pokemongostatus.org/

**Comment by iCreatZ** [comment]
servers are offline

**Comment by Marsinator** [comment]
niantic servers are slow. please wait for things to stabilize.

@devs: maybe we can surpress the output of those lines and give a proper error message instead?

#3293 #3294

**Comment by pehur** [comment]
Strangely my PTC account is still running strong

**Comment by dansali** [comment]
Seems its google's authentication servers for Pokemon Go that are having trouble, PTC seems to still work fine.

**Comment by dansali** [comment]
Also why closed? Could there be an exception catch to have a nicer message to say the API is slow/down?

**Comment by ChemiHatake** [comment]
@dansali Ill work on it

**Comment by draconiscor** [comment]
same

**Comment by alkolhar** [comment]
pokebot.ninja is still working, even with the google account

**Comment by FillNtheBlank** [comment]
Same - throws bot into a loop.  Can we make it just try to repeat whatever action it's trying to perform instead of sending it into an endless startup loop?

**Comment by Marsinator** [comment]
reopened.

**Comment by richard2191** [comment]
I'm having the same issue with my Google account. My PTC account is still working fine.

**Comment by a7mag3ddon** [comment]
My PTC account has same error as original poster so not related to google play logons. Will try again in an hour or so.

**Comment by zybertronix** [comment]
its server issue unstable check https://go.jooas.com/

**Comment by hammerhead13** [comment]
Looks like an Issue with this Bot. I am Able to use another and its working.

**Comment by a7mag3ddon** [comment]
hammerhead13  - What bot are you using ?

**Comment by hammerhead13** [comment]
PokeBuddy is the 1 i was using Prior to finding this one. I like Necro since its not so Resource Crazy. can run more than one nicely

**Comment by GitClucked** [comment]
Run more than one? Using the same account? Sorry. New to all of this haha

**Comment by a7mag3ddon** [comment]
ahh i tried pokebuddy, cant even get it log on using ptc. 

Like the idea of the realtime map though nice touch.

**Comment by rubstar** [comment]
I have the same issue but this usually happens after the bot runs for a while (10-15 minutes). This started when using 0.7.6, Never saw this issue before.

```
[21:33:42] Looking for incense Pokemon...
[21:33:42] Looking for Pokemon...
[21:33:42] Looking for incense Pokemon...
[21:33:43] Looking for Pokemon...
[21:33:44] Looking for incense Pokemon...
[21:33:44] Looking for Pokemon...
[21:33:45] Looking for incense Pokemon...
[21:33:46] Looking for Pokemon...
[21:33:46] Looking for incense Pokemon...
[21:33:47] Looking for Pokemon...
[21:33:48] Looking for incense Pokemon...
[21:33:48] Looking for Pokemon...
[21:33:49] Looking for incense Pokemon...
[21:33:50] Looking for Pokemon...
[21:33:50] Looking for incense Pokemon...
[21:33:51] Looking for Pokemon...
[21:33:51] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetItems>d__20.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 334
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetItemAmountByType>d__19.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 328
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass2_0.<<Execute>b__1>d.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
[21:33:51] Logging in using Google
```

**Comment by a7mag3ddon** [comment]
Working ok for me now im still using the original version ive been using for 2 days, i did nothing just waited and hour and tried again.

**Comment by looooozeeeeer** [comment]
will keep using 0.7.6 until this one is solved
