### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by TheGreatestDude** [NECROBOTIO/NecroBot#3319]
Hi,

I was running the bot, all seemed perfectly well. Steady stats, bot was going for 2 hours but then I switched back to it and found an awful lot of red text. I thought I was banned, then I saw the errors themselves and now I'm really confused! I have restarted the bot and it appears to work for about 5 pokestops then gives me the same error.

Here is the error:
[19:33:36] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<>c__DisplayClass0_1.<Execute>b__1(Candy q) in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 44
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__2.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 212
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass2_0.<<Execute>b__1>d.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

If anyone could explain this to me or provide a potential fix then I'd be very happy.

**Comment by quelladesoreta** [comment]
Same happens to me..

**Comment by olente2** [comment]
Same here. Anyone knows why?

**Comment by olente2** [comment]
Comunque su questo Github ci sono più italiani che altro..

**Comment by dansali** [comment]
Duplicate

https://github.com/NECROBOTIO/NecroBot/issues/3295

Pokemon servers are UNSTABLE!!!

**Comment by zybertronix** [comment]
one of my google account went like this. I Stop it for a moment and give it a break

**Comment by Sociopaat** [comment]
Same for me but it links to a different user, one that is not known on my pc (ciamo) :/

```
[20:58:25] System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:regel 408
```

**Comment by quelladesoreta** [comment]
It works well again for me now. The app on my phone works perfectly too. I don't even know..

**Comment by TheGreatestDude** [comment]
@dansali Sorry! I didn't mean to duplicate an issue, the one you referenced doesn't make it very clear in the title what the actual issue they are having is.

**Comment by nfettinger** [comment]
Server issue

**Comment by Sociopaat** [comment]
^
think so, restarted a few times didn't help
so i waited a little bit and now its running for 7 minutes

**Comment by a7mag3ddon** [comment]
I dont believe its the servers unstable, i am able to sign into the app without any issues, sign out and try the bot and fails same error.
