### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by KralElite** [NECROBOTIO/NecroBot#3473]
So this could be just me, but whenever I download necrobot (I have downloaded multiple times) It always fails to login.  (It will get stuck on "logging in").  The fix is to restart the program.  Not really a MAJOR issue but just wanted to share my findings

**Comment by schwartzadev** [comment]
What version is this?

**Comment by KralElite** [comment]
The most recent

**Comment by Marsinator** [comment]
we had this issue in one of our previous releases. try setting up necro from scratch

**Comment by buddiz87** [comment]
got an error using ptc account, it was running normally a minute ago
log:
[09:24:10] Name: Purple Rain Of Light XP: 50, Gems: 0, Items: 3 x ItemGreatBall, 1 x ItemPotion, Lat: 22.300092, Long: 114.174076
[09:24:15] Looking for Pokemon...
[09:24:15] Looking for incense Pokemon...
[09:24:17] Looking for Pokemon...
[09:24:17] Looking for incense Pokemon...
[09:24:18] Looking for Pokemon...
[09:25:59] Current Operation was canceled.
[09:25:59] Logging in using Ptc
[09:26:01] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by buddiz87** [comment]
it seems it is the ptc server problem, i can login now! thanks.

**Comment by thedarkfalcon** [comment]
I also have this problem. Cannot login using PTC, haven't botted for weeks because since necro 0.3, ptc has never worked for me. When it hangs on login, is it retrying? or has it just timed out and sits there indefinitely?

I hadn't tried necro for a while, so tried 0.7.7, then about a hour later when I tried again 0.7.8 was out. Neither appear to work for me.

After closing and opening necro several times (due to failed login), I then get a message saying "Connection refused. Your IP might have been Blacklisted by Niantic. Exiting.."
After changing external IP address, the process repeats itself. I don't understand why necro is having such a hard time logging in to the PTC server, I never have a problem when logging in via my phone or via NOX.

**Comment by thedarkfalcon** [comment]
I have attached a log from attempting to use necro 0.7.8 on a third machine, with a different external IP.

The bot doesn't appear to crash, but it stops logging. You can see at 04:11 that it stopped logging after asking for latitude, but it went on to ask for longitude, then attempted to connect (at which point it hung). After closing and reopening (the logs starting at 04:14) I get told my IP is black listed.

[Log.txt](https://github.com/NECROBOTIO/NecroBot/files/408188/Log.txt)

**Comment by nfettinger** [comment]
Server issue.
