### ISSUE TITLE
SystemNullReference Error

### ISSUE THREAD

**Issue by felangga** [NECROBOTIO/NecroBot#3508]
I want to report some error, running on my system. 

`[09:39:15] (Error) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36`

**Comment by schwartzadev** [comment]
After restarting necrobot, did this error persist?

**Comment by wele** [comment]
getting this all the time now as well

**Comment by GitClucked** [comment]
Same. Even restarted :P. Multiple topics have been created already as well.

**Comment by 20giis** [comment]
help please

**Comment by Jordan-Zhu** [comment]
Got new auth.json, restarted, and I'm still getting this error.

**Comment by felangga** [comment]
Yes, the error still show after restart

**Comment by felangga** [comment]
I think the error produced when I using PoGo Location feeder

**Comment by kfang1233** [comment]
I fixed this by turning off AutoUpdate in the config.

**Comment by Reborn1990** [comment]
[19:45:43] (ERROR) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__11.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

this is my error I'm getting. I run multiple bots and all of them are experiencing this issue. Resorted back to .7.6 and it seems to have resolved it.

**Comment by Mohammed9531** [comment]
Same here. It just started like few minutes ago.

**Comment by moghul91** [comment]
same here 

[10:57:12] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\InfoState.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by Reborn1990** [comment]
I am having this issue as well.

**Comment by Jordan-Zhu** [comment]
It must have been something in the update just now since before it was working fine all day

**Comment by Rick058** [comment]
Same issue, however I'm still on v.0.7.6 and my 2 PTC bots are working 10/10 where-as my Google account is in a permanent login loop with that error.

**Comment by thebsdteam** [comment]
you're right jordan . I used the bot yesterday all night , today without problem and i got this garbage bug when they updapted the bot ...

**Comment by felangga** [comment]
@Rick058 my PTC got the same login loop

**Comment by felangga** [comment]
So the solution is downgrade to 0.7.6 ?

**Comment by thebsdteam** [comment]
I read somewhere 0.7.2 is working fine.

**Comment by Jordan-Zhu** [comment]
Latest update 0.7.8 seems to have fixed the null reference exception. Turned off sniping at pokestops and it's working fine now

**Comment by Gorgoroth0030** [comment]
Works perfect for me when not using, PoGo Location feeder. Tested multiple times with/without sniping, and with/without PoGo Location feeder. Works fine while sniping without PoGo Location feeder.

**Comment by fartb0i** [comment]
@Gorgoroth0030 , That's right....everytime PoGo loc has connection issues....we get this error.

**Comment by thebsdteam** [comment]
System.NullReferenceException issue happen again but not that much as before...

**Comment by Jaysay1212** [comment]
duplicate #3500

**Comment by schwartzadev** [comment]
gratzi @Jaysay1212 
duplicate #3500
