### ISSUE TITLE
system null reference

### ISSUE THREAD

**Issue by dizzyddevil** [NECROBOTIO/NecroBot#3510]
[22:40:51] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemonFamilies>d__28.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext() in C:\Users\tvgfx\Documents\NECROBOTIO\NecroBot\PoGo.NecroBot.Logic\Tasks\DisplayPokemonStatsTask.cs:line 24

**Comment by 20giis** [comment]
me too!!

**Comment by Magnaleikha91** [comment]
Like mine right now :o

**Comment by Seyrenvox** [comment]
mine too XD

**Comment by vvvsrx** [comment]
me too~

**Comment by LTGRaven** [comment]
same

**Comment by Enragedmaster** [comment]
Same

**Comment by ridoknight** [comment]
same

**Comment by Magnaleikha91** [comment]
Since it's doesn't work and I have the previous version running well, I use the previous one for now.

**Comment by 20giis** [comment]
while everybody is here, does anyone have a 100k+ config? :santa:

**Comment by Reborn1990** [comment]
mine too. this is my data dump just posting for tracking.

[19:45:43] (ERROR) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__11.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by ryfoster** [comment]
same

**Comment by TheGreaper** [comment]
7.8 killed the programming wtf

**Comment by GitClucked** [comment]
I went back down to 7.2 and its working fine so far.

**Comment by canuckle604** [comment]
how do you go back to 7.2

**Comment by GitClucked** [comment]
Download it. :P. Just go back to the release page and download it.

**Comment by fartb0i** [comment]
It's running just fine on one of my logins... but other two (one google and one ptc) have the same issue.

**Comment by diogocmartins** [comment]
7.8 started runing fine again..

**Comment by P-rus** [comment]
I have a similar problem.  It seems intermittent.  I ran for 5 hours last night, then it stopped.  Again this morning for 3 hours.  Now it refuses to run at all.  Here's the text:

[error.docx](https://github.com/NECROBOTIO/NecroBot/files/408118/error.docx)

**Comment by 20giis** [comment]
it works now <3 <3

**Comment by Mohammed9531** [comment]
It's working fine now.

**Comment by nfettinger** [comment]
Duplicate of #3295
