### ISSUE TITLE
No usable PokeStops found in your area

### ISSUE THREAD

**Issue by erlbinary** [NECROBOTIO/NecroBot#3544]
After i update from 7.7 to 7.8 and this are the new error

Error 1
[10:55:06] (ERROR) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at PoGo.NecroBot.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__11.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Inventory.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.TransferDuplicatePokemonTask.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\TransferDuplicatePokemonTask.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PoGo.NecroBot.Logic.Tasks.CatchPokemonTask.<Execute>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchPokemonTask.cs:line 220
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.CatchNearbyPokemonsTask.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\CatchNearbyPokemonsTask.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<>c__DisplayClass2_0.<<Execute>b__1>d.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Navigation.<Move>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Navigation.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

Error 2

[11:25:44] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
[11:25:46] (UPDATE) [Evolves] Potential Evolves: 0
[11:25:48] (INFO) Amount of Pokemon Seen: 86/151, Amount of Pokemon Caught: 86/151
[11:25:48] (INFO) Pokeballs: 0 | Greatballs: 0 | Ultraballs: 120 | Masterballs: 0
[11:25:48] (INFO) Potions: 0 | SuperPotions: 0 | HyperPotions: 56 | MaxPotions: 24
[11:25:48] (INFO) Revives: 60 | MaxRevives: 0
[11:25:48] (INFO) Berrys: 48 | Incense: 9 | LuckyEggs: 6 | Lures: 6
[11:25:49] (EGG) Incubator status update: 2.00km left
[11:25:49] (EGG) Incubator status update: 2.02km left
[11:25:49] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
[11:25:51] (UPDATE) [Evolves] Potential Evolves: 0
[11:25:53] (INFO) Amount of Pokemon Seen: 86/151, Amount of Pokemon Caught: 86/151
[11:25:53] (INFO) Pokeballs: 0 | Greatballs: 0 | Ultraballs: 120 | Masterballs: 0
[11:25:53] (INFO) Potions: 0 | SuperPotions: 0 | HyperPotions: 56 | MaxPotions: 24
[11:25:53] (INFO) Revives: 60 | MaxRevives: 0
[11:25:53] (INFO) Berrys: 48 | Incense: 9 | LuckyEggs: 6 | Lures: 6
[11:25:53] (EGG) Incubator status update: 2.00km left
[11:25:53] (EGG) Incubator status update: 2.02km left
[11:25:54] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?
[11:25:55] (UPDATE) [Evolves] Potential Evolves: 0
[11:25:58] (INFO) Amount of Pokemon Seen: 86/151, Amount of Pokemon Caught: 86/151
[11:25:58] (INFO) Pokeballs: 0 | Greatballs: 0 | Ultraballs: 120 | Masterballs: 0
[11:25:58] (INFO) Potions: 0 | SuperPotions: 0 | HyperPotions: 56 | MaxPotions: 24
[11:25:58] (INFO) Revives: 60 | MaxRevives: 0
[11:25:58] (INFO) Berrys: 48 | Incense: 9 | LuckyEggs: 6 | Lures: 6
[11:25:59] (EGG) Incubator status update: 2.00km left
[11:25:59] (EGG) Incubator status update: 2.02km left
[11:25:59] (ATTENTION) No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by blaketek14** [comment]
same here

**Comment by Jaysay1212** [comment]
In config.json try changing "SnipingScanOffset": to 0.013

Solved when I had the same issue

**Comment by danooh** [comment]
What walking km/h do you guys use?

**Comment by blaketek14** [comment]
15 km/h

**Comment by Jaysay1212** [comment]
I user 31.0km/h

**Comment by danooh** [comment]
Mine was 31.0km/h first as well. changing it to 15 worked for me. but still does not solve blaketek14's problem... i thought it was about the new 'speed limit' implemented in the newest android / ios version, which was released some hours ago.
tryin' to figure it out

**Comment by Rick058** [comment]
This is what I did https://github.com/NECROBOTIO/NecroBot/issues/3255#issuecomment-238303920 
It might help, it did seem to work for me every time I had this Pokestops error.

**Comment by blaketek14** [comment]
tks Rick058, it works

**Comment by SDMU** [comment]
so the no usable pokestop message being displayed continuously is actually the 'unban in 1/45  2/45 ' message ?

**Comment by erlbinary** [comment]
After i update from 7.7 to 7.8 the error message displayed after i run the program

**Comment by Rick058** [comment]
@SDMU Not that I think. I'm guessing it is because you log in from a certain IP address that has been flagged for some reason (running more than 3 bots at a time for example). Been trying to figure out what the problem was for quite some time yesterday. Came to the conclusion that running more than 3 bots caused the loop of softbans and when restarting the bot a loop of 'No usable Pokestops found'. 
Apparently switching to another IP and starting your bot again fixed the issue. Due to connecting from a non-flagged IP it forced the account to find a Pokestop and get rid of the softban (1/45 - 45/45). After that, I waited a couple of minutes and closed my VPN. 
No errors ever since I have done that and went back to 3 bots at a time instead of 4+

Hope it's a bit clear now, it's late for me and my English is noticeably getting worse... 6 AM. If you need help, @ mention me or pm me. I'll check when I'm awake. I'm no coder/developer though, but I have some basic knowledge.

**Comment by 17yongga** [comment]
@Rick058 The VPN fixed the loop problem.

**Comment by Otar666** [comment]
Check if you got this... (ERROR) Niantic Servers unstable, throttling API Calls.
If you do, thats the issue, when the server gets back to responding, everything gets back to normal, no msgs sent. My case took 3 mins of that same message, over and over and over... And that is way better then 7.7

**Comment by 17yongga** [comment]
I did not get that message, I waited for 30 mins and it did not show up, opening VPN worked.

**Comment by schwartzadev** [comment]
solved

**Comment by mza2k16** [comment]
I just updated to the newest version 0.8.1 and I am getting the error No Usable Pokestops, I haven't been able to get this working since day one; I have tried the method described above about turning on hide.me VPN still no luck.

**Comment by macshadow** [comment]
SOLUTION 
https://github.com/NECROBOTIO/NecroBot/compare/master...macshadow:patch-1
