### ISSUE TITLE
InvalidResponseException and relogin

### ISSUE THREAD

**Issue by roytam1** [NECROBOTIO/NecroBot#3674]
pmgo server seems throwing invalid response which makes necrobot asking for user to press a key:
```
[15:37:54] (ERROR) System.AggregateException: One or more errors occurred. ---> PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<UpdatePlayerLocation>d__1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Snipe>d__6.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Snipe>d__6.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 379
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Execute>d__5.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 229
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
---> (Inner Exception #0) PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProtoPayload>d__7`2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Player.<UpdatePlayerLocation>d__1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Player.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Snipe>d__6.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Snipe>d__6.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 379
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Execute>d__5.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 229<---
[15:37:54] (INFO) Logging in using Ptc
[15:37:55] (INFO) Playing as PMGOPlayer
[15:37:56] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 22.412345678901 Lng: 114.123456789012
[15:37:56] (INFO) Program will continue after the key press...
```

**Comment by liweichen6** [comment]
Met this before, I guess, (not sure) it's caused by unstable connection.
Set "welcome delay" to "false" and bot won't ask for key press again.

**Comment by roytam1** [comment]
@liweichen6 thanks for welcome delay tips. :)
