### ISSUE TITLE
Problem help!

### ISSUE THREAD

**Issue by kilycba** [NECROBOTIO/NecroBot#4008]
i get this error on the last update... i checkd the coords 2 times and r fine... what can i do?

[14:49:53] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 19
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by theloser** [comment]
Post your

>   "DefaultLatitude": ???,
>  "DefaultLongitude": ???,

**Comment by kilycba** [comment]
"DefaultLatitude": -31.4207828
"DefaultLongitude": -64.49921388888889

Are from Villa Carlos Paz Argentina

**Comment by MetaExtreme** [comment]
use have to use a "," like this

"DefaultLatitude": -31.4207828,
"DefaultLongitude": -64.49921388888889,

**Comment by kilycba** [comment]
already done, but same error appears

**Comment by MetaExtreme** [comment]
try to use less numbers like that
"DefaultLatitude": -31.420782,
"DefaultLongitude": -64.4992138,
maybe it works

**Comment by nfettinger** [comment]
Please use the Discord chat rooms for general help.
