### ISSUE TITLE
Crash at first pokestop when "GetSniperInfoFromPokeSnipers" (row 60 in config) is true

### ISSUE THREAD

**Issue by BjornMagn** [NECROBOTIO/NecroBot#4095]
Title says it all. I believe this option was added in the most recent patch (0.8.1). Not sure what it's supposed to do, but feels weird that it was set to true by default (It was for me atleast, if I recall correctly)
![crash 0 8 1](https://cloud.githubusercontent.com/assets/14334856/17532394/9ff802ee-5e80-11e6-80a0-d64fa4df60df.PNG)

Error message is in Swedish, but here are a few translations:
"Indatasträngen hade ett ....." = The indata string wasn't correctly formatted
"Vid" = at
"-- Slut på stackspårningen från...." = End of stacktracking from recent place where an exception was triggered (roughly)

**Comment by nfettinger** [comment]
For general help and Configuration questions, please use our Discord chat channels.
Sounds like one of your filters is set wrong or a Pokename is spelled wrong

**Comment by khellang** [comment]
I'm seeing the same:

> [21:54:23] (ERROR) System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.GetSniperInfoFrom_pokesnipers(ISession session, List`1 pokemonIds) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 627
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Execute>d__5.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 268
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36

**Comment by nfettinger** [comment]
Make sure you are using periods instead of commas in the coordinates.

**Comment by BjornMagn** [comment]
Bot works fine when this value is set to false (sniper too). Haven't had a problem with my config before this patch. I'm not using commas in the coordinates, will check my config for other fuck ups an extra time but I'd be pretty surprised if there's anything to find.

**Comment by jjskuld** [comment]
I think this is an issue with the pokesnipers parsing code when you are not using English.  It should be already be fixed in the master code, so the fix should go out with 0.8.2.  For now disable by setting it to false in the config.

**Comment by khellang** [comment]
I don't use parameters anywhere. This is a culture bug. My computer has a Norwegian culture, which uses comma as the decimal separator. There's ano InvariantCulture argument missing somewhere.
