### ISSUE TITLE
(ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90

### ISSUE THREAD

**Issue by iqbalsuzetta** [NECROBOTIO/NecroBot#4209]
(EGG) Incubator status update: 0,50km left
[07.52.48] (ERROR) System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 19
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 36
[07.52.48] (EGG) Incubator status update: 1,37km left

**Comment by palooga** [comment]
`Argument must be in range of -90 to 90
Parameter name: Latitude
at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value)`

Your latitude is wrong. Can you not see that in the error?

**Comment by iqbalsuzetta** [comment]
thanks
