### ISSUE TITLE
Bot Only Working 30 minutes

### ISSUE THREAD

**Issue by gapracoolz** [NECROBOTIO/NecroBot#4255]
i use necrobot but it's only working 30 minutes after that kick out from niantic api...please fix it...i only use 1 IP 2 bot...but it's always working only for 30 minutes.

**Comment by Rick058** [comment]
Do you have any examples? Error log, screenshot, mistake in your config perhaps? 
I'm currently having 2 sessions of 8 hours of straight botting without facing any problems.

**Comment by brightjoyy** [comment]
me too

**Comment by gapracoolz** [comment]
[09:50:41] Niantic Servers unstable, throttling API Calls.
[09:50:42] System.Net.WebException: The remote name could not be resolved: 'sso.pokemon.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
[09:50:46] Niantic Servers unstable, throttling API Calls.
[09:51:04] System.Net.WebException: The remote name could not be resolved: 'sso.pokemon.com'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

it's the error log....i only edit config for latlong and snipe pokemon.

**Comment by recon88** [comment]
Try using only one bot on one IP
