### ISSUE TITLE
ApiFailureStrategy NPE

### ISSUE THREAD

**Issue by m-kubis** [NECROBOTIO/NecroBot#4281]
relevant log file content:
[15:54:51] Pokemon Inventory is full, transferring Pokemon...
[15:54:53] Looking for Pokemon...
[15:54:54] Pokemon Inventory is full, transferring Pokemon...
[15:54:57] Looking for incense Pokemon...
[15:54:58] Pokemon Inventory is full, transferring Pokemon...
[15:54:59] Looking for Pokemon...
[15:55:01] Pokemon Inventory is full, transferring Pokemon...
[15:55:03] Looking for incense Pokemon...
[15:55:04] Pokemon Inventory is full, transferring Pokemon...
[15:55:05] Name: Landscape Restoration Plaque XP: 50, Gems: 0, Items: 3 x ItemPokeBall, Lat: 40.774727, Long: -73.969296
[15:55:05] Not enough Pokeballs to start sniping! (86/100)
[15:55:08] Looking for Pokemon...
[15:55:09] Pokemon Inventory is full, transferring Pokemon...
[15:55:14] Looking for incense Pokemon...
[15:55:15] Name: Trefoil Arch XP: 50, Gems: 0, Items: 1 x ItemUltraBall, 2 x ItemPokeBall, Lat: 40.774598, Long: -73.968942
[15:55:15] Not enough Pokeballs to start sniping! (89/100)
[15:55:16] Looking for Pokemon...
[15:55:18] Pokemon Inventory is full, transferring Pokemon...
[15:55:19] Looking for incense Pokemon...
[15:55:20] Looking for Pokemon...
[15:55:20] Looking for incense Pokemon...
[15:55:22] Looking for Pokemon...
[15:55:22] Looking for incense Pokemon...
[15:55:23] Name: American Elm Plaque Crosstown Tree Walk XP: 50, Gems: 0, Items: 2 x ItemPokeBall, 1 x ItemRevive, Lat: 40.774629, Long: -73.969918
[15:55:23] Not enough Pokeballs to start sniping! (89/100)
[15:55:25] Looking for Pokemon...
[15:55:26] Looking for incense Pokemon...
[15:55:27] Looking for Pokemon...
[15:55:27] Looking for incense Pokemon...
[15:55:28] Pokemon Inventory is full, transferring Pokemon...
[15:55:29] Looking for Pokemon...
[15:55:30] Looking for incense Pokemon...
[15:55:32] Pokemon Inventory is full, transferring Pokemon...
[15:55:33] Looking for Pokemon...
[15:55:35] Pokemon Inventory is full, transferring Pokemon...
[15:55:37] Looking for incense Pokemon...
[15:55:38] Pokemon Inventory is full, transferring Pokemon...
[16:04:53] Current Operation was canceled.
[16:04:53] Logging in using Ptc
[16:06:23] Exceptiion caught, writing LogBuffer.

console output:

```cs
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Unhandled. Crashes the app.

Version: 0.8.0
Windows Version: 7 64bit

**Comment by nfettinger** [comment]
Duplicate #3295
