### ISSUE TITLE
Can somebody explain this log to me? Despawned? SoftBanned? No Usable PokeStops?

### ISSUE THREAD

**Issue by jayhao2000** [NECROBOTIO/NecroBot#4296]
**[15:46:42] (localhost) Sniping a Slowbro with Unknown IV at 32.686666,-117.166133...
[15:46:43] Did not find a Pokemon within the Location, pokemon despawned?
[15:46:48] (localhost) Sniping a Vaporeon with Unknown IV at 1.380419,103.767613...
[15:46:49] Did not find a Pokemon within the Location, pokemon despawned?
[15:46:54] (localhost) Sniping a Slowbro with Unknown IV at 25.768899,-80.132259...
[15:46:54] Did not find a Pokemon within the Location, pokemon despawned?
[15:46:59] (localhost) Sniping a Lickitung with Unknown IV at 39.955733,-75.156863...
[15:47:00] Did not find a Pokemon within the Location, pokemon despawned?
[15:47:05] (localhost) Sniping a Muk with Unknown IV at 22.322867,114.256927...
[15:47:06] Did not find a Pokemon within the Location, pokemon despawned?**
[15:47:11] (Pokezz.com) Connection Error
[15:47:28] Pokemon Servers might be offline / unstable. Trying again...
[15:47:29] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.GetSniperInfoFrom_pokesnipers(ISession session, List`1 pokemonIds) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 651
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Execute>d__5.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 278
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 216
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 56
[15:47:29] Logging in using Google
[15:47:31] Playing as Lanjiao
[15:47:31] Detected realistic Traveling , using Default Settings inside config.json
[15:47:31] Make sure Lat & Lng are right. Exit Program if not! Lat: 5.41723782357778 Lng: 100.330912787283
[15:47:31] ====== DisplayHighestsCP ======
[15:47:31] # CP 1636/1688 | (76.96% perfect)	| Lvl 20	 NAME: Exeggutor 	 MOVE1: ZenHeadbuttFast      MOVE2: Psychic              Candy: 50
[15:47:31] # CP 1612/1705 | (59.21% perfect)	| Lvl 20	 NAME: Arcanine  	 MOVE1: BiteFast             MOVE2: Flamethrower         Candy: 19
[15:47:31] # CP 1154/1261 | (40.10% perfect)	| Lvl 17	 NAME: Slowbro   	 MOVE1: ConfusionFast        MOVE2: Psychic              Candy: 23
[15:47:31] # CP 1098/1141 | (75.39% perfect)	| Lvl 18	 NAME: Tentacruel	 MOVE1: PoisonJabFast        MOVE2: Blizzard             Candy: 10
[15:47:31] # CP 1060/1138 | (56.94% perfect)	| Lvl 20	 NAME: Seaking   	 MOVE1: PeckFast             MOVE2: Megahorn             Candy: 16
[15:47:31] # CP 1020/1097 | (47.61% perfect)	| Lvl 13	 NAME: Exeggutor 	 MOVE1: ConfusionFast        MOVE2: SolarBeam            Candy: 50
[15:47:31] # CP  995/1020 | (85.45% perfect)	| Lvl 19	 NAME: Magneton  	 MOVE1: ThunderShockFast     MOVE2: FlashCannon          Candy: 56
[15:47:31] # CP  977/1074 | (47.20% perfect)	| Lvl 20	 NAME: Magneton  	 MOVE1: SparkFast            MOVE2: FlashCannon          Candy: 56
[15:47:31] # CP  958/ 976 | (89.77% perfect)	| Lvl 21	 NAME: Lickitung 	 MOVE1: LickFast             MOVE2: HyperBeam            Candy: 3
[15:47:31] # CP  932/ 987 | (68.60% perfect)	| Lvl 21	 NAME: Electrode 	 MOVE1: SparkFast            MOVE2: Thunderbolt          Candy: 45
[15:47:31] ====== DisplayHighestsPerfect ======
[15:47:31] # CP  590/ 599 | (91.91% perfect)	| Lvl 12	 NAME: Dragonair 	 MOVE1: DragonBreathFast     MOVE2: AquaTail             Candy: 18
[15:47:31] # CP  211/ 215 | (91.47% perfect)	| Lvl 07	 NAME: Kabuto    	 MOVE1: ScratchFast          MOVE2: AncientPower         Candy: 3
[15:47:31] # CP  958/ 976 | (89.77% perfect)	| Lvl 21	 NAME: Lickitung 	 MOVE1: LickFast             MOVE2: HyperBeam            Candy: 3
[15:47:31] # CP  465/ 472 | (88.03% perfect)	| Lvl 05	 NAME: Dragonite 	 MOVE1: SteelWingFast        MOVE2: HyperBeam            Candy: 18
[15:47:31] # CP  995/1020 | (85.45% perfect)	| Lvl 19	 NAME: Magneton  	 MOVE1: ThunderShockFast     MOVE2: FlashCannon          Candy: 56
[15:47:31] # CP  214/ 222 | (78.33% perfect)	| Lvl 04	 NAME: Pinsir    	 MOVE1: FuryCutterFast       MOVE2: Submission           Candy: 7
[15:47:31] # CP  322/ 338 | (77.28% perfect)	| Lvl 11	 NAME: Eevee     	 MOVE1: TackleFast           MOVE2: BodySlam             Candy: 13
[15:47:31] # CP 1636/1688 | (76.96% perfect)	| Lvl 20	 NAME: Exeggutor 	 MOVE1: ZenHeadbuttFast      MOVE2: Psychic              Candy: 50
[15:47:31] # CP 1098/1141 | (75.39% perfect)	| Lvl 18	 NAME: Tentacruel	 MOVE1: PoisonJabFast        MOVE2: Blizzard             Candy: 10
[15:47:31] # CP  125/ 142 | (71.93% perfect)	| Lvl 19	 NAME: Magikarp  	 MOVE1: SplashFast           MOVE2: Struggle             Candy: 127
[15:47:31] Potential Evolutions: 0
**[15:47:32] Incubator status update: 2.30km left
[15:47:32] Incubator status update: 4.10km left
[15:47:32] Incubator status update: 4.36km left
[15:47:32] Incubator status update: 2.30km left
[15:47:32] Incubator status update: 1.36km left
[15:47:32] Incubator status update: 2.30km left**
[15:47:33] Amount of Pokemon Seen: 97/151, Amount of Pokemon Caught: 97/151
[15:47:33] No usable PokeStops found in your area. Is your maximum distance too small?
[15:47:33] Potential Evolutions: 0
[15:47:33] Incubator status update: 2.30km left
[15:47:33] Incubator status update: 4.10km left
[15:47:33] Incubator status update: 4.36km left
[15:47:33] Incubator status update: 2.30km left
[15:47:33] Incubator status update: 1.36km left
[15:47:33] Incubator status update: 2.30km left
[15:47:34] Amount of Pokemon Seen: 97/151, Amount of Pokemon Caught: 97/151
[15:47:35] No usable PokeStops found in your area. Is your maximum distance too small?
[15:47:36] Potential Evolutions: 0
[15:47:36] Incubator status update: 2.30km left
[15:47:36] Incubator status update: 4.10km left
[15:47:36] Incubator status update: 4.36km left
[15:47:36] Incubator status update: 2.30km left
[15:47:36] Incubator status update: 1.36km left
[15:47:36] Incubator status update: 2.30km left
[15:47:37] Amount of Pokemon Seen: 97/151, Amount of Pokemon Caught: 97/151
[15:47:37] No usable PokeStops found in your area. Is your maximum distance too small?
[15:47:38] Potential Evolutions: 0
[15:47:38] Amount of Pokemon Seen: 97/151, Amount of Pokemon Caught: 97/151
[15:47:38] Incubator status update: 2.30km left
[15:47:38] Incubator status update: 4.10km left
[15:47:38] Incubator status update: 4.36km left
[15:47:38] Incubator status update: 2.30km left
[15:47:38] Incubator status update: 1.36km left
[15:47:38] Incubator status update: 2.30km left
[15:47:40] No usable PokeStops found in your area. Is your maximum distance too small?
[15:47:40] Potential Evolutions: 0
[15:47:40] Amount of Pokemon Seen: 97/151, Amount of Pokemon Caught: 97/151
[15:47:41] Incubator status update: 2.30km left
[15:47:41] Incubator status update: 4.10km left
[15:47:41] Incubator status update: 4.36km left
[15:47:41] Incubator status update: 2.30km left
[15:47:41] Incubator status update: 1.36km left
[15:47:41] Incubator status update: 2.30km left
[15:47:41] No usable PokeStops found in your area. Is your maximum distance too small?

**Comment by jayhao2000** [comment]
{
  "TranslationLanguageCode": "en",
  "AutoUpdate": true,
  "TransferConfigAndAuthOnUpdate": true,
  "UseWebsocket": false,
  "WebSocketPort": 14251,
  "StartupWelcomeDelay": false,
  "UseTelegramAPI": false,
  "TelegramAPIKey": null,
  "AmountOfPokemonToDisplayOnStart": 10,
  "DetailedCountsBeforeRecycling": false,
  "MaxBerriesToUsePerPokemon": 3,
  "CatchPokemon": true,
  "AutomaticallyLevelUpPokemon": false,
  "OnlyUpgradeFavorites": true,
  "UseLevelUpList": true,
  "AmountOfTimesToUpgradeLoop": 5,
  "GetMinStarDustForLevelUp": 5000,
  "LevelUpByCPorIv": "iv",
  "UpgradePokemonCpMinimum": 1000.0,
  "UpgradePokemonIvMinimum": 95.0,
  "UpgradePokemonMinimumStatsOperator": "and",
  "DisableHumanWalking": false,
  "DefaultLatitude": 5.417427,
  "DefaultLongitude": 100.33111,
  "WalkingSpeedInKilometerPerHour": 10.0,
  "MaxSpawnLocationOffset": 10,
  "FastSoftBanBypass": false,
  "DelayBetweenPlayerActions": 5000,
  "DelayBetweenPokemonCatch": 2000,
  "DumpPokemonStats": false,
  "EvolveAboveIvValue": 95.0,
  "EvolveAllPokemonAboveIv": false,
  "EvolveAllPokemonWithEnoughCandy": true,
  "EvolveKeptPokemonsAtStorageUsagePercentage": 90.0,
  "KeepPokemonsThatCanEvolve": false,
  "KeepMinCp": 800,
  "KeepMinIvPercentage": 90.0,
  "KeepMinLvl": 6,
  "KeepMinOperator": "or",
  "UseKeepMinLvl": false,
  "PrioritizeIvOverCp": false,
  "KeepMinDuplicatePokemon": 1,
  "UseGpxPathing": false,
  "GpxFile": "GPXPath.GPX",
  "VerboseRecycling": true,
  "RecycleInventoryAtUsagePercentage": 90.0,
  "RandomizeRecycle": false,
  "RandomRecycleValue": 5,
  "DelayBetweenRecycleActions": false,
  "UseEggIncubators": true,
  "UseLuckyEggConstantly": false,
  "UseLuckyEggsMinPokemonAmount": 30,
  "UseLuckyEggsWhileEvolving": false,
  "UseIncenseConstantly": false,
  "UseBerriesMinCp": 1000,
  "UseBerriesMinIv": 90.0,
  "UseBerriesBelowCatchProbability": 0.2,
  "UseBerriesOperator": "or",
  "UseSnipeLocationServer": true,
  "SnipeLocationServer": "localhost",
  "SnipeLocationServerPort": 16969,
  "GetSniperInfoFromPokezz": true,
  "GetOnlyVerifiedSniperInfoFromPokezz": true,
  "GetSniperInfoFromPokeSnipers": true,
  "GetSniperInfoFromPokeWatchers": true,
  "SnipeWithSkiplagged": true,
  "MinPokeballsToSnipe": 20,
  "MinPokeballsWhileSnipe": 0,
  "MinDelayBetweenSnipes": 60000,
  "SnipingScanOffset": 0.003,
  "SnipeAtPokestops": false,
  "SnipeIgnoreUnknownIv": false,
  "UseTransferIvForSnipe": false,
  "SnipePokemonNotInPokedex": false,
  "RenamePokemon": false,
  "RenameOnlyAboveIv": true,
  "RenameTemplate": "{1}_{0}",
  "MaxPokeballsPerPokemon": 6,
  "MaxTravelDistanceInMeters": 1000,
  "TotalAmountOfPokeballsToKeep": 120,
  "TotalAmountOfPotionsToKeep": 80,
  "TotalAmountOfRevivesToKeep": 60,
  "TotalAmountOfBerriesToKeep": 50,
  "UseGreatBallAboveCp": 1000,
  "UseUltraBallAboveCp": 1250,
  "UseMasterBallAboveCp": 1500,
  "UseGreatBallAboveIv": 85.0,
  "UseUltraBallAboveIv": 95.0,
  "UseGreatBallBelowCatchProbability": 0.2,
  "UseUltraBallBelowCatchProbability": 0.1,
  "UseMasterBallBelowCatchProbability": 0.05,
  "EnableHumanizedThrows": false,
  "NiceThrowChance": 40,
  "GreatThrowChance": 30,
  "ExcellentThrowChance": 10,
  "CurveThrowChance": 90,
  "ForceGreatThrowOverIv": 90.0,
  "ForceExcellentThrowOverIv": 95.0,
  "ForceGreatThrowOverCp": 1000,
  "ForceExcellentThrowOverCp": 1500,
  "TransferWeakPokemon": false,
  "TransferDuplicatePokemon": true,
  "TransferDuplicatePokemonOnCapture": true,
  "FavoriteMinIvPercentage": 95.0,
  "AutoFavoritePokemon": false,
  "UsePokemonToNotCatchFilter": false,
  "UsePokemonSniperFilterOnly": false,
  "ItemRecycleFilter": [
    {
      "Key": "itemUnknown",
      "Value": 0
    },
    {
      "Key": "itemLuckyEgg",
      "Value": 200
    },
    {
      "Key": "itemIncenseOrdinary",
      "Value": 100
    },
    {
      "Key": "itemIncenseSpicy",
      "Value": 100
    },
    {
      "Key": "itemIncenseCool",
      "Value": 100
    },
    {
      "Key": "itemIncenseFloral",
      "Value": 100
    },
    {
      "Key": "itemTroyDisk",
      "Value": 100
    },
    {
      "Key": "itemXAttack",
      "Value": 100
    },
    {
      "Key": "itemXDefense",
      "Value": 100
    },
    {
      "Key": "itemXMiracle",
      "Value": 100
    },
    {
      "Key": "itemSpecialCamera",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasicUnlimited",
      "Value": 100
    },
    {
      "Key": "itemIncubatorBasic",
      "Value": 100
    },
    {
      "Key": "itemPokemonStorageUpgrade",
      "Value": 100
    },
    {
      "Key": "itemItemStorageUpgrade",
      "Value": 100
    }
  ],
  "PokemonsNotToTransfer": [
    "venusaur",
    "charizard",
    "blastoise",
    "clefable",
    "muk",
    "chansey",
    "gyarados",
    "ditto",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dragonite",
    "mewtwo",
    "mew"
  ],
  "PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata"
  ],
  "PokemonsToLevelUp": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsToIgnore": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "doduo"
  ],
  "PokemonsTransferFilter": {
    "Golduck": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Farfetchd": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Krabby": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Kangaskhan": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Horsea": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Staryu": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "MrMime": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 40.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Scyther": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jynx": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Electabuzz": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magmar": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Pinsir": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Tauros": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Magikarp": {
      "KeepMinCp": 200,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Gyarados": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Lapras": {
      "KeepMinCp": 1800,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 80.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Eevee": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 95.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Vaporeon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Jolteon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Flareon": {
      "KeepMinCp": 1500,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Porygon": {
      "KeepMinCp": 1250,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 60.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Snorlax": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    },
    "Dragonite": {
      "KeepMinCp": 2600,
      "KeepMinLvl": 6,
      "UseKeepMinLvl": false,
      "KeepMinIvPercentage": 90.0,
      "KeepMinDuplicatePokemon": 1,
      "Moves": [],
      "KeepMinOperator": "or",
      "MovesOperator": "or"
    }
  },
  "PokemonToSnipe": {
    "Locations": [
      {
        "Latitude": 38.556807486461118,
        "Longitude": -121.2383794784546
      },
      {
        "Latitude": -33.859019,
        "Longitude": 151.213098
      },
      {
        "Latitude": 47.5014969,
        "Longitude": -122.0959568
      },
      {
        "Latitude": 51.5025343,
        "Longitude": -0.2055027
      }
    ],
    "Pokemon": [
      "venusaur",
      "charizard",
      "blastoise",
      "beedrill",
      "raichu",
      "sandslash",
      "nidoking",
      "nidoqueen",
      "clefable",
      "ninetales",
      "golbat",
      "vileplume",
      "golduck",
      "primeape",
      "arcanine",
      "poliwrath",
      "alakazam",
      "machamp",
      "golem",
      "rapidash",
      "slowbro",
      "farfetchd",
      "muk",
      "cloyster",
      "gengar",
      "exeggutor",
      "marowak",
      "hitmonchan",
      "lickitung",
      "rhydon",
      "chansey",
      "kangaskhan",
      "starmie",
      "mrMime",
      "scyther",
      "magmar",
      "electabuzz",
      "jynx",
      "gyarados",
      "lapras",
      "ditto",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dragonite",
      "mewtwo",
      "mew"
    ]
  },
  "PokemonToUseMasterball": [
    "articuno",
    "zapdos",
    "moltres",
    "mew",
    "mewtwo"
  ]
}

**Comment by theloser** [comment]
Possible softban.

**Comment by jayhao2000** [comment]
how can i solve this? it keeps on recurring after running just a few minutes.

**Comment by nfettinger** [comment]
Duplicate #3295
