### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by djordjeb123** [NECROBOTIO/NecroBot#4373]
[10:05:16] (UPDATE) New update detected, would you like to update? Y/N
[10:05:16] (INFO) Your IP is: 109.165.174.129
y
[10:05:18] (UPDATE) Downloading and apply Update...
https://github.com/NecronomiconCoding/NecroBot/releases/download/v0.8.4/Release.zip
C:\Users\Djordje Bunic\Desktop\snipe\Release\Release.zip
[10:05:29] (UPDATE) Finished downloading newest Release...
[10:05:29] (UPDATE) Finished unpacking files...
[10:05:29] (UPDATE) Update finished, you can close this window now.
[10:05:29] (INFO) Exception caught, writing LogBuffer.

Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Users\Djordje Bunic\Desktop\snipe\Release\config\auth.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at PoGo.NecroBot.Logic.AuthSettings.Save(String fullPath) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 172
   at PoGo.NecroBot.Logic.AuthSettings.Load(String path) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 129
   at PoGo.NecroBot.Logic.GlobalSettings.Load(String path, Boolean boolSkipSave) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Settings.cs:line 854
   at PoGo.NecroBot.Logic.State.StateMachine.<>c__DisplayClass3_0.<Start>b__0(Object sender, FileSystemEventArgs e) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 46
   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
[10:05:30] (UPDATE) Finished transferring your config to the new version...
Ending Application...5

**Comment by palooga** [comment]
Make sure the bot is closed and anything using the bot is closed.

**Comment by ruchern** [comment]
@palooga You are using the bot to update and you expect to close the bot to run the update?

It doesn't make sense when it worked previously.

**Comment by nfettinger** [comment]
This is not a NecroBOT error, but a platform one.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
