### ISSUE TITLE
After v0.8.4 update my bot is not working

### ISSUE THREAD

**Issue by nyae3000** [NECROBOTIO/NecroBot#4384]
[16:12:37] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -33.87206
5,151.208195...
[16:12:45] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -37.57814
,144.922...
[16:12:47] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:12:47] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 53.376694
,-6.277755...
[16:12:51] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:12:51] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 41.640467
,-4.734827...
[16:12:51] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:12:51] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 51.507351
,-0.127758...
[16:12:52] (INFO) Traveling to Pokestop: 275 George St Art Panel (71m) (2 second
s)
[16:12:53] (INFO) Skipped Zubat
[16:12:54] (POKESTOP) Name: 275 George St Art Panel XP: 50, Gems: 0, Items: 1 x
ItemPotion, 1 x ItemPokeBall, 1 x ItemUltraBall, Lat: -33.865274, Long: 151.2071
82
[16:13:03] (ERROR) (Pokezz.com) Connection Error
[16:13:11] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 35.632896
4,139.8803943...
[16:13:11] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:11] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 40.712784
,-74.005941...
[16:13:12] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 38.907192
,-77.036871...
[16:13:12] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 37.77493,
-122.419416...
[16:13:12] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 52.520007
,13.404954...
[16:13:13] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:13] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 45.030148
,-93.319312...
[16:13:13] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -33.87206
5,151.208195...
[16:13:18] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -37.57814
,144.922...
[16:13:19] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:19] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 53.376694
,-6.277755...
[16:13:19] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:19] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 41.640467
,-4.734827...
[16:13:20] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:20] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 51.507351
,-0.127758...
[16:13:23] (INFO) Traveling to Pokestop: Menzies Hotel Clock (63m) (2 seconds)
[16:13:24] (INFO) Skipped Zubat
[16:13:25] (POKESTOP) Name: Menzies Hotel Clock XP: 50, Gems: 0, Items: 2 x Item
GreatBall, 1 x ItemPokeBall, Lat: -33.865375, Long: 151.206511
[16:13:27] (EVOLVED) Potential Evolutions: 113
[16:13:27] (UPDATE) Waiting to evolve 113 Pokemon once 47 more are caught! (170/
217 for 90% inventory)
[16:13:27] (INFO) No Incense Available
[16:13:28] (TRANSFERRED) Caterpie       - CP:  107  IV:  29.47%   [Best CP:  277
  IV:  17.78%] (Candies: 185)
[16:13:31] (INFO) Amount of Pokemon Seen: 62/151, Amount of Pokemon Caught: 59/1
51
[16:13:32] (ERROR) (Pokezz.com) Connection Error
[16:13:39] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 35.632896
4,139.8803943...
[16:13:39] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:39] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 40.712784
,-74.005941...
[16:13:43] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 38.907192
,-77.036871...
[16:13:43] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:43] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 37.77493,
-122.419416...
[16:13:44] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 52.520007
,13.404954...
[16:13:44] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:44] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 45.030148
,-93.319312...
[16:13:44] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -33.87206
5,151.208195...
[16:13:45] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -37.57814
,144.922...
[16:13:46] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:46] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 53.376694
,-6.277755...
[16:13:47] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:47] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 41.640467
,-4.734827...
[16:13:47] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:13:47] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 51.507351
,-0.127758...
[16:13:48] (INFO) Traveling to Pokestop: John Dunmore Lang Statue (44m) (1 secon
ds)
[16:13:51] (INFO) Skipped Zubat
[16:13:52] (POKESTOP) Name: John Dunmore Lang Statue XP: 50, Gems: 0, Items: 1 x
 ItemGreatBall, 3 x ItemPokeBall, Lat: -33.865449, Long: 151.20604
[16:14:04] (ERROR) (Pokezz.com) Connection Error
[16:14:06] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[16:14:07] (ERROR) Error: System.NullReferenceException: Object reference not se
t to an instance of an object.
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.GetSniperInfoFrom_pokesnipers(I
Session session, List`1 pokemonIds) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo
.NecroBot.Logic\Tasks\SnipePokemonTask.cs:line 650
   at PoGo.NecroBot.Logic.Tasks.SnipePokemonTask.<Execute>d__5.MoveNext() in C:\
Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\SnipePokemonTask.cs:
line 277
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:
\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.c
s:line 216
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\c
iamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\
ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 56
[16:14:07] (INFO) Logging in using Google
[16:14:09] (INFO) Playing as BoyBlas
[16:14:10] (ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat:
-33.865449 Lng: 151.20604
[16:14:10] (INFO) ====== DisplayHighestsCP ======
[16:14:10] (INFO) # CP 1630/1700 | (66.94% perfect)     | Lvl 17         NAME: D
ragonite         MOVE1: SteelWingFast        MOVE2: DragonClaw           Candy:
15
[16:14:10] (INFO) # CP 1434/1519 | (58.14% perfect)     | Lvl 18         NAME: E
xeggutor         MOVE1: ConfusionFast        MOVE2: SeedBomb             Candy:
34
[16:14:10] (INFO) # CP 1266/1351 | (53.46% perfect)     | Lvl 16         NAME: E
xeggutor         MOVE1: ConfusionFast        MOVE2: Psychic              Candy:
34
[16:14:10] (INFO) # CP 1265/1334 | (61.44% perfect)     | Lvl 15         NAME: S
norlax           MOVE1: ZenHeadbuttFast      MOVE2: HyperBeam            Candy:
31
[16:14:10] (INFO) # CP 1177/1237 | (74.06% perfect)     | Lvl 30         NAME: R
aticate          MOVE1: QuickAttackFast      MOVE2: HyperFang            Candy:
465
[16:14:10] (INFO) # CP 1176/1278 | (40.19% perfect)     | Lvl 15         NAME: A
rcanine          MOVE1: FireFangFast         MOVE2: Flamethrower         Candy:
11
[16:14:10] (INFO) # CP 1111/1253 | (20.62% perfect)     | Lvl 17         NAME: V
enusaur          MOVE1: RazorLeafFast        MOVE2: PetalBlizzard        Candy:
10
[16:14:10] (INFO) # CP 1077/1126 | (68.29% perfect)     | Lvl 14         NAME: V
aporeon          MOVE1: WaterGunFast         MOVE2: HydroPump            Candy:
56
[16:14:10] (INFO) # CP 1049/1210 | (16.08% perfect)     | Lvl 20         NAME: E
lectabuzz        MOVE1: LowKickFast          MOVE2: Thunder              Candy:
11
[16:14:10] (INFO) # CP  972/ 989 | (88.84% perfect)     | Lvl 16         NAME: A
erodactyl        MOVE1: BiteFast             MOVE2: IronHead             Candy:
15
[16:14:10] (INFO) ====== DisplayHighestsPerfect ======
[16:14:10] (INFO) # CP  154/ 154 | (100.00% perfect)    | Lvl 08         NAME: S
pearow           MOVE1: PeckFast             MOVE2: DrillPeck            Candy:
33
[16:14:10] (INFO) # CP  279/ 282 | (95.24% perfect)     | Lvl 12         NAME: E
kans             MOVE1: AcidFast             MOVE2: SludgeBomb           Candy:
16
[16:14:10] (INFO) # CP  281/ 289 | (92.50% perfect)     | Lvl 15         NAME: C
hansey           MOVE1: ZenHeadbuttFast      MOVE2: Psychic              Candy:
3
[16:14:10] (INFO) # CP  354/ 360 | (91.24% perfect)     | Lvl 07         NAME: T
auros            MOVE1: TackleFast           MOVE2: Earthquake           Candy:
3
[16:14:10] (INFO) # CP  675/ 686 | (90.20% perfect)     | Lvl 14         NAME: J
ynx              MOVE1: FrostBreathFast      MOVE2: Psyshock             Candy:
3
[16:14:10] (INFO) # CP  972/ 989 | (88.84% perfect)     | Lvl 16         NAME: A
erodactyl        MOVE1: BiteFast             MOVE2: IronHead             Candy:
15
[16:14:10] (INFO) # CP  496/ 510 | (87.44% perfect)     | Lvl 16         NAME: B
ellsprout        MOVE1: AcidFast             MOVE2: Wrap                 Candy:
3
[16:14:10] (INFO) # CP  453/ 469 | (82.61% perfect)     | Lvl 11         NAME: M
r. Mime          MOVE1: ZenHeadbuttFast      MOVE2: Psychic              Candy:
3
[16:14:10] (INFO) # CP  913/ 937 | (81.37% perfect)     | Lvl 11         NAME: L
apras            MOVE1: FrostBreathFast      MOVE2: IceBeam              Candy:
19
[16:14:10] (INFO) # CP  290/ 304 | (81.35% perfect)     | Lvl 12         NAME: P
ikachu           MOVE1: ThunderShockFast     MOVE2: Thunderbolt          Candy:
14
[16:14:10] (EVOLVED) Potential Evolutions: 113
[16:14:10] (UPDATE) Waiting to evolve 113 Pokemon once 48 more are caught! (169/
217 for 90% inventory)
[16:14:10] (INFO) No Incense Available
[16:14:11] (EGG) Incubator status update: 3.75km left
[16:14:11] (EGG) Incubator status update: 4.35km left
[16:14:11] (EGG) Incubator status update: 1.37km left
[16:14:11] (EGG) Incubator status update: 4.53km left
[16:14:11] (EGG) Incubator status update: 0.27km left
[16:14:11] (EGG) Incubator status update: 5.00km left
[16:14:11] (EGG) Incubator status update: 8.75km left
[16:14:11] (EGG) Incubator status update: 3.75km left
[16:14:13] (INFO) Amount of Pokemon Seen: 62/151, Amount of Pokemon Caught: 59/1
51
[16:14:15] (INFO) Traveling to Pokestop: Wynyard Train Station (46m) (1 seconds)

[16:14:18] (PKMN) (CatchSuccess) | (Lure) NidoranFemale Lvl: 14 CP: (277/350) IV
: 13.00% | Chance: 40.01% | 0.00m dist | with a PokeBall (127 left). | 210 EXP e
arned | Candies: 3 | lat: -33.865614 long: 151.205586
[16:14:23] (POKESTOP) Name: Wynyard Train Station XP: 50, Gems: 0, Items: 2 x It
emPokeBall, 1 x ItemRevive, 1 x ItemRazzBerry, Lat: -33.865614, Long: 151.205586

[16:14:26] (ERROR) (Pokezz.com) Connection Error
[16:14:33] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 35.632896
4,139.8803943...
[16:14:34] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:14:34] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 40.712784
,-74.005941...
[16:14:37] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 38.907192
,-77.036871...
[16:14:44] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:14:44] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 37.77493,
-122.419416...
[16:14:49] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 52.520007
,13.404954...
[16:14:59] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 45.030148
,-93.319312...
[16:14:59] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -33.87206
5,151.208195...
[16:15:01] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -37.57814
,144.922...
[16:15:01] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:15:01] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 53.376694
,-6.277755...
[16:15:02] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:15:02] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 41.640467
,-4.734827...
[16:15:02] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:15:02] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 51.507351
,-0.127758...
[16:15:03] (INFO) Traveling to Pokestop: 33 York Artwork (59m) (2 seconds)
[16:15:05] (POKESTOP) Name: 33 York Artwork XP: 50, Gems: 0, Items: 1 x ItemGrea
tBall, 2 x ItemPokeBall, Lat: -33.86614, Long: 151.205646
[16:15:14] (ERROR) (Pokezz.com) Connection Error
[16:15:27] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 35.632896
4,139.8803943...
[16:15:27] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:15:27] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 40.712784
,-74.005941...
[16:15:32] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 38.907192
,-77.036871...
[16:15:32] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:15:32] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 37.77493,
-122.419416...
[16:15:33] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 52.520007
,13.404954...
[16:15:34] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 45.030148
,-93.319312...
[16:15:34] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -33.87206
5,151.208195...
[16:15:38] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at -37.57814
,144.922...
[16:15:38] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:15:38] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 53.376694
,-6.277755...
[16:15:38] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:15:38] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 41.640467
,-4.734827...
[16:15:39] (SNIPER) Did not find a Pokemon within the Location, pokemon despawne
d?
[16:15:39] (SNIPER) (Skiplagged.com) Scanning for Snipeable Pokemon at 51.507351
,-0.127758...
[16:15:49] (INFO) Traveling to Pokestop: York Street Ventilation Column (29m) (1
 seconds)
[16:15:51] (POKESTOP) Name: York Street Ventilation Column XP: 50, Gems: 0, Item
s: 2 x ItemPotion, 1 x ItemPokeBall, Lat: -33.866223, Long: 151.205942
[16:16:11] (ERROR) (Pokezz.com) Connection Error

**Comment by feroniameimei** [comment]
change your ip address, then start bot from first step when bot asked your username/password.

**Comment by nyae3000** [comment]
where in config?

**Comment by iimkku** [comment]
wiki - getting started

**Comment by recon88** [comment]
Set SnipingScanOffset to 0.01
