### ISSUE TITLE
necrobot 0.8.5 crash

### ISSUE THREAD

**Issue by Dr-Death** [NECROBOTIO/NecroBot#4400]
necrobot from V0.8.2 to 0.8.5 crash.

logs:
> [10.12.14] <> Exception caught, writing LogBuffer.
> 
> Unhandled Exception: System.NullRefernceException: Object reference not set to an instance of an object.
> 	at PoGo.NecroBot.CLI.Program.CheckKillSwitch<>
> 	at PoGo.NecroBot.CLI.Program.Main<String[] args>

**Comment by Kjewn** [comment]
0.8.5??

**Comment by necr-0** [comment]
@Kjewn,

Nothing special.
Just removes some 3rd party code.

**Comment by michael8228** [comment]
keep crashing for me

**Comment by andreseveres** [comment]
can't find pokestop nearby... wtf

**Comment by rafnix29** [comment]
me too cant find pokestops nearby. how much bots can i run? when i start 2 bots i will become softbann

**Comment by andreseveres** [comment]
i run 5 bots no ban in 8.4 version

**Comment by jumpcom** [comment]
me too in 0.8.5

**Comment by andreseveres** [comment]
8.5 keep cant find pokestop... hmmm

**Comment by rafnix29** [comment]
andreseveres do you use proxy or all bots from same ip?

**Comment by narendrawi** [comment]
[15:49:46] Incubator status update: 1.92km left
[15:49:46] Incubator status update: 1.08km left
[15:49:46] Amount of Pokemon Seen: 58/151, Amount of Pokemon Caught: 56/151
[15:49:46] Pokemon Servers might be offline / unstable. Trying again...
[15:49:48] Error: System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PoGo.NecroBot.Logic.Utils.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Utils\LocationUtils.cs:line 19
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsTask.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 56
[15:49:48] Logging in using Google 





**after update , clash bot , please advices**

**Comment by justrk** [comment]
I goot the same issue
Run only 1 bot with 15kmh

**Comment by Sanafan** [comment]
same here, no pokestops

**Comment by Dr-Death** [comment]
i use proxy

**Comment by narendrawi** [comment]
hi DR-Death , use proxy ? or VPN ?

**Comment by Dr-Death** [comment]
i use http proxy "solipo" with TOR socks5, but necrobot.exe crash before creating "auth.json"

**Comment by nfettinger** [comment]
Duplicate #3295
