### ISSUE TITLE
referencing missing file

### ISSUE THREAD

**Issue by ev4ng3l1n3** [NECROBOTIO/NecroBot#4412]
Thrown this exception after printing the inventory to start a recycle.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Common\ApiF
ailureStrategy.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncC
tx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Version: 0.8.4
Windows Version: win 10

**Comment by Kjewn** [comment]
Whats in line 136

**Comment by Kjewn** [comment]
"Key": "itemTroyDisk",

Lookup the real value of this, or remove it.

**Comment by ev4ng3l1n3** [comment]
What file you're talking about?

Because it seems that it's trying to reference this file: C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs:line 136

There's no user called ciamo on my machine.

**Comment by thedarkfalcon** [comment]
Do you have a dump of your config file available? Ensure that you have **UseGpxPathing** set to _false_

**Comment by nfettinger** [comment]
Duplicate #3295
