### ISSUE TITLE
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kauegimenes** [NECROBOTIO/NecroBot#4458]
The bot was running fine for a few hours and this happened.

```
[02:02:53] (INFO) Exception caught, writing LogBuffer.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by ASKcoTM** [comment]
this was fixed for me when i updated to 0.8.5 so im not sure. if it dosn't work, try re-downloading.

**Comment by kauegimenes** [comment]
@ASKcoTM oh, ok. Just updated.

**Comment by nfettinger** [comment]
Duplicate #3295
