### ISSUE TITLE
Wont start, no error message... someone help please?

### ISSUE THREAD

**Issue by IrradiatedDovahkiin** [NECROBOTIO/NecroBot#4560]
I Opened NecroBot this morning, and it did the insta-crash where it doesnt start at all, but gives error. figuring i just needed a new version, i downloaded the newest one(0.8.5), and this is is what it told me after i re-registered my account for the bot...

Initializing NecroBot logger at time 8/10/2016 8:52:52 AM...
[08:52:53] Your IP is: 50.116.51.227
[08:52:53] Perfect! You already have the newest Version 0.8.5
[08:52:53] Logging in using Google
[08:53:21] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35
[08:53:41] Logging in using Google
[08:54:08] System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35
Initializing NecroBot logger at time 8/10/2016 8:54:22 AM...

And then it insta-crashed again, no error code,,, help please

**Comment by nfettinger** [comment]
Please reboot your machine. If that doesnt work, then you are blacklisted from the login server.

Please seek general help and answers to configuration questions to our Discord chat rooms. These issues are meant for code development only.
