### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by stevenemoyee** [NECROBOTIO/NecroBot#4576]
having issues ...
[01:36:50] (INFO) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'pgorelease.nianticlabs.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Helpers\RetryHandler.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs:line 35

it does not log me into my account somehow...

**Comment by nfettinger** [comment]
Your VPN or Proxy hostname could not be resolved
Please use Discord chat for theses types of issues and questions.
