### ISSUE TITLE
help im new and dont understand this error message

### ISSUE THREAD

**Issue by maxsum15** [NECROBOTIO/NecroBot#4980]
[16:08:39] Pokemon Servers might be offline / unstable. Trying again...
[16:08:40] Error: System.IO.FileNotFoundException: Could not find file 'C:\Users\maxsu\Desktop\Release\GPXPath.GPX'.
File name: 'C:\Users\maxsu\Desktop\Release\GPXPath.GPX'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.GetGpxTracks(ISession session) in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 189
   at PoGo.NecroBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__1.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\FarmState.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\StateMachine.cs:line 56

**Comment by theloser** [comment]
It says clearly "Could not find file 'C:\Users\maxsu\Desktop\Release\GPXPath.GPX'.". Nothing I can add to this.

And please, this does not ssem to be a development issue or a bug. More like a config issue.
Please use the [Discord channels](https://discord.gg/VXKxNFr) to get help with your questions.
Thanks!

**Comment by ausscheider** [comment]
when you don't have a gpx file

make this
"UseGpxPathing": false,

**Comment by maxsum15** [comment]
Thank you and that's exactly what I did and its up and running.

**Comment by theloser** [comment]
Great!

Please close this issue, and thank you using the issue tracker :-)

**Comment by nfettinger** [comment]
We can not help you with setup or configuration items here. This space is for code development issues only. Please use our Discord chat room #support for further assistance.
