### ISSUE TITLE
Telegram error

### ISSUE THREAD

**Issue by kuity** [NECROBOTIO/NecroBot#5151]
### Expected Behavior
Telegram commands should work with my bot. e.g. /top

### Actual Behavior
Nothing is working.
The log is showing this error:
```Unkown Telegram Error occured.```

### Your config.json
These are the only lines I changed:
```
"UseTelegramAPI": true,
"TelegramAPIKey": "<my_api_key>",
```

### Steps to Reproduce
Just run NecroBot after updating the above two lines in the config.,

### Other Information

I have tried debugging and an exception is occurring on line 38 in TelegramService.cs:
```var me = _bot.GetMeAsync().Result;```

Following is what I get after printing the Exception.Message and Exception.InnerException:
```
[01:03:40] Unkown Telegram Error occured. One or more errors occurred.System.Security.VerificationException: Method System.Net.Http.CloneableExtensions.Clone: type argument 'System.Net.Http.Headers.MediaTypeHeaderValue' violates the constraint of type parameter 'T'.
   at System.Net.Http.Formatting.MediaTypeConstants.get_ApplicationJsonMediaType()
   at System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor()
   at System.Net.Http.Formatting.MediaTypeFormatterCollection.CreateDefaultFormatters()
   at System.Net.Http.HttpContentExtensions.get_DefaultMediaTypeFormatterCollection()
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__139`1.MoveNext()
```

**Comment by ChemiHatake** [comment]
#4947

**Comment by kuity** [comment]
Ok, I merged your branch but getting a strange error where once I set the TelegramAPIKey and try to run NecroBot, it keeps restarting. 

This is what the log shows:
```
Initializing NecroBot logger at time 8/12/2016 2:30:28 AM...
Initializing NecroBot logger at time 8/12/2016 2:30:32 AM...
Initializing NecroBot logger at time 8/12/2016 2:30:35 AM...
Initializing NecroBot logger at time 8/12/2016 2:30:38 AM...
Initializing NecroBot logger at time 8/12/2016 2:30:41 AM...
```

**Comment by nfettinger** [comment]
Duplicate issue. Please wait for the next release
