### ISSUE TITLE
Can't log in google account

### ISSUE THREAD

**Issue by hibc25311** [NECROBOTIO/NecroBot#5297]
This only happens to my google account , however my ptc account work fine 

[10:16:40] (UPDATE) Perfect! You already have the newest Version 0.8.5
[10:16:40] (INFO) Logging in using Google
[10:16:41] (INFO) Your IP is: 
[10:16:41] (INFO) System.NullReferenceException: Object reference not set to an instance of an object.
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformAuthRequest(Dictionary`2 data)
   at DankMemes.GPSOAuthSharp.GPSOAuthClient.PerformMasterLogin(String service, String deviceCountry, String operatorCountry, String lang, Int32 sdkVersion)
   at PokemonGo.RocketAPI.Login.GoogleLogin.<GetAccessToken>d__3.MoveNext() at C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Login\GoogleLogin.cs: line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() at C:\Users\ciamo\Source\Repos\NecroBot\FeroxRev\PokemonGo.RocketAPI\Rpc\Login.cs: line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext() at C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\State\LoginState.cs: line 35

**Comment by smoothrunnings** [comment]
@hibc25311 Check your google password. If you have an Android device look on there. I find my Samsung Note 5 prompts me to enter in my Google password at least 4 times a day.

**Comment by hibc25311** [comment]
NO, there is no similar message on my device thanks for your suggestion

**Comment by leonnjh** [comment]
Have you tried going in to the auth file with notepad in Config folder? You can check to make sure your details are correct.

**Comment by hibc25311** [comment]
@leonnjh I think that should be correct because this problem happend first several hours ago

**Comment by martionhotmail** [comment]
I got the same issue

**Comment by recon88** [comment]
Please check https://www.reddit.com/r/pokemongodev/comments/4xct8f/psa_permabans_have_arrived_stop_all_use_of_3rd/
