### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by pluem544** [NECROBOTIO/NecroBot#5322]
[09:41:36] System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
at Interop.mincore.TryGetErrorMessage(IntPtr moduleHandle, Int32 errorCode, StringBuilder sb, String& errorMsg)
at Interop.mincore.GetMessage(IntPtr moduleHandle, Int32 errorCode)
at System.Net.Http.WinHttpException.GetErrorMessage(Int32 error)
at System.Net.Http.WinHttpHandler.SetRequestHandleDecompressionOptions(SafeWinHttpHandle requestHandle)
at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
at System.Net.Http.WinHttpHandler.d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PokemonGo.RocketAPI.Helpers.RetryHandler.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at PokemonGo.RocketAPI.Helpers.RetryHandler.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.HttpClient.d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

**Comment by Sanskritmp** [comment]
https://www.microsoft.com/en-US/download/details.aspx?id=30653

**Comment by Itsapaul** [comment]
Getting the same error and that download says I have the same or newer version installed already
