### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll'

### ISSUE THREAD

**Issue by rebopro** [NECROBOTIO/NecroBot#5327]
Initializing NecroBot logger at time 12/8/2016 7:47:04 AM...
[07:47:08] Perfect! You already have the newest Version 0.8.6
[07:47:08] Logging in using Google
[07:47:08] Your IP is: XXX.XXX.XXX.XXX
[07:47:34] System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(IntPtr moduleHandle, Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(IntPtr moduleHandle, Int32 errorCode)
   at System.Net.Http.WinHttpException.GetErrorMessage(Int32 error)
   at System.Net.Http.WinHttpHandler.SetRequestHandleDecompressionOptions(SafeWinHttpHandle requestHandle)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext()
[07:47:54] Logging in using Google
[07:48:21] System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(IntPtr moduleHandle, Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(IntPtr moduleHandle, Int32 errorCode)
   at System.Net.Http.WinHttpException.GetErrorMessage(Int32 error)
   at System.Net.Http.WinHttpHandler.SetRequestHandleDecompressionOptions(SafeWinHttpHandle requestHandle)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext()
Initializing NecroBot logger at time 12/8/2016 7:49:20 AM...

**Comment by zappiy** [comment]
Lol thats happening to me now. At first it was constant soft bans and now this.

**Comment by JonSuperKnife** [comment]
same

**Comment by jatinkapoor7** [comment]
same

**Comment by JonSuperKnife** [comment]
and before this gets taken down its not a problem with my framework im at latest version

**Comment by R0jo** [comment]
same

**Comment by zappiy** [comment]
Well time to go to sleep and see if time will resolve this issue lol.

**Comment by PalmerX** [comment]
I fix it by installing C++ Redistributable https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by JonSuperKnife** [comment]
didnt work now its a different error

**Comment by JonSuperKnife** [comment]
an error occured while sending the request

**Comment by rebopro** [comment]
@PalmerX thanks it worked for me too!
