### ISSUE TITLE
pokemon server might be offline?

### ISSUE THREAD

**Issue by kurozani** [NECROBOTIO/NecroBot#5331]
what?

updated to 8.6 and got thiissss
it was so smoootth in 8.5

**Comment by lilybluecat** [comment]
same here

`[12:01:31] Make sure Lat & Lng are right. Exit Program if not! Lat: 13.8632197171134 Lng: 100.718593263532
[12:01:56] Pokemon Servers might be offline / unstable. Trying again...
[12:01:57] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
Initializing NecroBot logger at time 8/12/2016 12:03:32 PM...
`

**Comment by kurozani** [comment]
use nox to make sure, it looks like it really is offline??

**Comment by JayTang** [comment]
it seems 8.6 get u banned

**Comment by kurozani** [comment]
whaatt?? --"

**Comment by pussypump** [comment]
server is down tried on my cellphone

**Comment by kurozani** [comment]
let's see, I am trying using a different account

**Comment by JayTang** [comment]
try another account, server is not down.

**Comment by bitsukukoy** [comment]
still working

**Comment by GoGoDong** [comment]
Same here, tried on my iPhone, same.
Tried to log another account of same IP, succeeded.
Seems my bot account got hard banned.

**Comment by pussypump** [comment]
The mest have taken non-cheating players with them - i see complaining comming :P
