### ISSUE TITLE
Getting a server may be offline error? Only for one account, but others are fine?

### ISSUE THREAD

**Issue by yoyoyo2010** [NECROBOTIO/NecroBot#5341]
[22:21:30] Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7711370098693 Lng: -73.9742695343872
[22:21:55] Pokemon Servers might be offline / unstable. Trying again...
[22:21:56] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
Initializing NecroBot logger at time 8/11/2016 10:22:24 PM...
[22:22:25] Perfect! You already have the newest Version 0.8.6
[22:22:25] Logging in using Google

**Comment by Zaryabb** [comment]
same im getting this as well on 8.6

**Comment by alek30** [comment]
same here please help

**Comment by yoyoyo2010** [comment]
I tried logging in an alt account and there wasn't a problem. I found out it stopped working after i came back home leaving it on for a few hours. This has happened in 0.8.5 and 0.8.6

**Comment by markemonb** [comment]
Same here, think it's really a server error on which the specific accounts are hosted

**Comment by nexteve** [comment]
I think the pogo's server is really offline...it's really a server error

**Comment by markemonb** [comment]
My first error log was at 
 4:29 AM CEST

**Comment by Logitech88** [comment]
ya only pokemon go login with google error if u used ptc wasnt

**Comment by danooh** [comment]
i used ptc on my bot. cannot log in either.

**Comment by nerclid** [comment]
Same issue, only one of my accounts. Others are fine.

**Comment by HydraXHydra** [comment]
same here just using 10min then server might be offline ;*(

**Comment by nexteve** [comment]
and i try another account to login. it fine. Nintendo baned our accounts?

**Comment by Logitech88** [comment]
may be i dont know brother but if i used another account still fine omg my pokemon miss :(
