### ISSUE TITLE
v0.8.6 problem

### ISSUE THREAD

**Issue by michael8228** [NECROBOTIO/NecroBot#5369]
Anybody encountering this?

(ATTENTION) Make sure Lat & Lng are right. Exit Program if not! Lat: 40.7851319565244 Lng: -73.9683504042279
[14:21:06] (ERROR) Pokemon Servers might be offline / unstable. Trying again...
[14:21:07] (ERROR) Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
```

**Comment by zzxxzzxxSG** [comment]
Server issue, Change location to another Country.

**Comment by avikapoor** [comment]
yes. same error
![error copy paste](https://cloud.githubusercontent.com/assets/13604912/17614503/87fb1536-6084-11e6-854f-7db243ab4579.PNG)

**Comment by michael8228** [comment]
i am sorry but where do i change the location on 0.8.6?

**Comment by avikapoor** [comment]
michael8228  , what is your location in game ?

**Comment by LTGRaven** [comment]
necrobot just crashes every time i start it up

**Comment by DagooNn** [comment]
"Failed to get game data from the server." is this server issue or perm ban?

**Comment by michael8228** [comment]
singapore
