### ISSUE TITLE
i downloaded and configured the new 0.8.6 necro bot but whenever i am trying to start the app it shows me this error(necrobot client for pokemon go has stopped working) and shows me 2 option(end the programme(2)check internet for solution) please help me

### ISSUE THREAD

**Issue by ApoorvMane** [NECROBOTIO/NecroBot#5394]

**Comment by ashleynohay** [comment]
@ApoorvMane update your .net framework to the latest

**Comment by WaterFl0ws** [comment]
usually there is something error with your config, either lack of " or ,

**Comment by norwin23** [comment]
same problem with mine too.

**Comment by Coesuke** [comment]
i've update framework but still ds't work

**Comment by felpapa** [comment]
Hi I have the same problem. It seems to be with connection. This was the error:

C:\temp\Release>NecroBot.exe
[08:52:17] () Exception caught, writing LogBuffer.

Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'PokemonGo.RocketAPI.HttpClient.PokemonHttpClient' threw an exception. ---> Sy
stem.TypeLoadException: Could not load type 'System.Security.Authentication.SslP
rotocols' from assembly 'System.Net.Primitives, Version=4.0.0.0, Culture=neutral
, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Net.Http.HttpClientHandler..ctor()
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..cctor()
   --- End of inner exception stack trace ---
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..ctor()
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy a
piFailureStrategy)
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings
 logicSettings)
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings
 logicSettings)
   at PoGo.NecroBot.CLI.Program.Main(String[] args)

**Comment by recon88** [comment]
For help or configuration questions visit https://discord.gg/VXKxNFr
Also use the ticket template instead of removing it and don't put everything in title.
