### ISSUE TITLE
could not login nable to load DLL 'api-ms-win-core-localization-l1-2-0.dll'

### ISSUE THREAD

**Issue by arrows88** [NECROBOTIO/NecroBot#5400]
[15:20:35] (UPDATE) Perfect! You already have the newest Version 0.8.6
[15:20:35] (INFO) Logging in using Google
[15:20:35] (INFO) Your IP is: 
[15:21:01] (INFO) System.DllNotFoundException: Unable to load DLL 'api-ms-win-co
re-localization-l1-2-0.dll': The specified module could not be found. (Exception
 from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource, UInt32 dwMes
sageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] argume
nts)
   at Interop.mincore.TryGetErrorMessage(IntPtr moduleHandle, Int32 errorCode, S
tringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(IntPtr moduleHandle, Int32 errorCode)
   at System.Net.Http.WinHttpException.GetErrorMessage(Int32 error)
   at System.Net.Http.WinHttpHandler.SetRequestHandleDecompressionOptions(SafeWi
nHttpHandle requestHandle)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState
 state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext()
[15:21:21] (INFO) Logging in using Google
[15:21:47] (INFO) System.DllNotFoundException: Unable to load DLL 'api-ms-win-co
re-localization-l1-2-0.dll': The specified module could not be found. (Exception
 from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource, UInt32 dwMes
sageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] argume
nts)
   at Interop.mincore.TryGetErrorMessage(IntPtr moduleHandle, Int32 errorCode, S
tringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(IntPtr moduleHandle, Int32 errorCode)
   at System.Net.Http.WinHttpException.GetErrorMessage(Int32 error)
   at System.Net.Http.WinHttpHandler.SetRequestHandleDecompressionOptions(SafeWi
nHttpHandle requestHandle)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState
 state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext()
[15:22:07] (INFO) Logging in using Google
[15:22:33] (INFO) System.DllNotFoundException: Unable to load DLL 'api-ms-win-co
re-localization-l1-2-0.dll': The specified module could not be found. (Exception
 from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource, UInt32 dwMes
sageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] argume
nts)
   at Interop.mincore.TryGetErrorMessage(IntPtr moduleHandle, Int32 errorCode, S
tringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(IntPtr moduleHandle, Int32 errorCode)
   at System.Net.Http.WinHttpException.GetErrorMessage(Int32 error)
   at System.Net.Http.WinHttpHandler.SetRequestHandleDecompressionOptions(SafeWi
nHttpHandle requestHandle)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState
 state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext()
[15:22:53] (INFO) Logging in using Google
[15:23:19] (INFO) System.DllNotFoundException: Unable to load DLL 'api-ms-win-co
re-localization-l1-2-0.dll': The specified module could not be found. (Exception
 from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource, UInt32 dwMes
sageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] argume
nts)
   at Interop.mincore.TryGetErrorMessage(IntPtr moduleHandle, Int32 errorCode, S
tringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(IntPtr moduleHandle, Int32 errorCode)
   at System.Net.Http.WinHttpException.GetErrorMessage(Int32 error)
   at System.Net.Http.WinHttpHandler.SetRequestHandleDecompressionOptions(SafeWi
nHttpHandle requestHandle)
   at System.Net.Http.WinHttpHandler.SetRequestHandleOptions(WinHttpRequestState
 state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__101.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at PokemonGo.RocketAPI.Helpers.RetryHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProto>d__2`1.Move
Next()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.BaseRpc.<PostProto>d__14`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.State.LoginState.<Execute>d__0.MoveNext()

**Comment by mogibilal** [comment]
try open in your smartphone, hope dont get baned

**Comment by pixerx** [comment]
same

**Comment by pixerx** [comment]
work fine in smartphone, cant login in bot.

**Comment by Joloxx9** [comment]
Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll

Sma eproblem here windows 7 Embedded.

And people stop talking shit about bans, that's bot error not not stupid bans.

**Comment by pixerx** [comment]
yup something wrong with the bot setting, not ban. Different behavior.

**Comment by AnantaSetya** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145

hope solve it

**Comment by arrows88** [comment]
https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145
