### ISSUE TITLE
Pokemon Servers might be offline / unstable. Trying again..

### ISSUE THREAD

**Issue by 777333** [NECROBOTIO/NecroBot#5410]
I keep getting an error when logging in. Anyone have any idea what's wrong or how to fix it? I'm pretty sure the Lat/Lng is correct. 

00:24:49] Perfect! You already have the newest Version 0.8.6
[00:24:49] Logging in using Ptc
[00:24:49] Your IP is: *********
[00:25:23] Playing as ***
[00:25:24] Make sure Lat & Lng are right. Exit Program if not! Lat: 37.8020441018713 Lng: -122.396733662733
[00:25:48] Pokemon Servers might be offline / unstable. Trying again...
[00:25:49] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Inventory.<GetPokemons>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.Inventory.<GetHighestsCp>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.NecroBot.Logic.Tasks.DisplayPokemonStatsTask.<Execute>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.InfoState.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.NecroBot.Logic.State.StateMachine.<Start>d__3.MoveNext()
Initializing NecroBot logger at time 8/12/2016 12:28:15 AM...
[00:28:16] JSON Exception: After parsing a value an unexpected character was encountered: ". Path 'DefaultLatitude', line 27, position 2.
[00:28:16] Exception caught, writing LogBuffer.
Initializing NecroBot logger at time 8/12/2016 12:28:22 AM...
[00:28:23] JSON Exception: After parsing a value an unexpected character was encountered: ". Path 'DefaultLatitude', line 27, position 2.
[00:28:23] Exception caught, writing LogBuffer.
Initializing NecroBot logger at time 8/12/2016 12:28:40 AM...
Initializing NecroBot logger at time 8/12/2016 12:29:21 AM...

**Comment by Disane87** [comment]
#5388

**Comment by 777333** [comment]
Are you sure it's the same problem? Is there anyway to determine whether or not I've been banned?

**Comment by kurozani** [comment]
sam issue

**Comment by halowarsss** [comment]
Same! Everything was oky, but after install 0.86, i get this error all the time!
