### ISSUE TITLE
Release_0_8_6 crashing on windows Server 2008

### ISSUE THREAD

**Issue by Jaxone** [NECROBOTIO/NecroBot#5420]
Tried to install new version from scratch on windows 2008 and it crashes with new config , old config, no config.
---

Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'PokemonGo.RocketAPI.HttpClient.PokemonHttpClient' threw an exception. ---> Sy
stem.TypeLoadException: Could not load type 'System.Security.Authentication.SslP
rotocols' from assembly 'System.Net.Primitives, Version=4.0.0.0, Culture=neutral
, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Net.Http.HttpClientHandler..ctor()
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..cctor()
   --- End of inner exception stack trace ---
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..ctor()
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy a
piFailureStrategy)
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings
 logicSettings)
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings
 logicSettings)
   at PoGo.NecroBot.CLI.Program.Main(String[] args)
-----------
Error log says : 
Initializing NecroBot logger at time 8/12/2016 10:11:35 AM...
[10:11:36] Exception caught, writing LogBuffer.
Initializing NecroBot logger at time 8/12/2016 10:14:08 AM...
[10:14:09] Exception caught, writing LogBuffer.
Initializing NecroBot logger at time 8/12/2016 10:14:42 AM...
[10:14:43] Exception caught, writing LogBuffer.

Crashes even with empty config.
Tested on two systems both runing windows 2008 R2.

Anything I can log more to see where the error is ?

Thanks in advance.

**Comment by chohitoshiri** [comment]
Check .netframework version first....should be 4.6.2 at least....

**Comment by Jaxone** [comment]
I will check,  but don't think this is the problem. Will update the issue in 30 minute

**Comment by Jaxone** [comment]
Well, updating to 4.6.2 did help.
Why would the bin be compiled with latest .net and use some osbscure component that does not work with all .net versions ?
Seems a bit strange ... 
If I would have to make my code I would use an older .net version to be sure is compatible with 99% of the systems out there.

Thanks anyway.
