### ISSUE TITLE
crashed..

### ISSUE THREAD

**Issue by TagorHP** [NECROBOTIO/NecroBot#5435]
![untitled](https://cloud.githubusercontent.com/assets/18613376/17617544/f5e24694-60a4-11e6-96fe-bda4b03a36c2.jpg)

[15:40:16] (ERROR) Causing Method: System.Collections.Generic.Dictionary`2[System.String,System.String] PerformAuthRequest(System.Collections.Generic.Dictionary`2[System.String,System.String]) Source: GPSOAuthSharp Data: System.Collections.ListDictionaryInternal
[15:40:16] (INFO) Exception caught, writing LogBuffer.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.NecroBot.Logic.Common.ApiFailureStrategy.<DoLogin>d__5.MoveNext() in C:\Users\ciamo\Source\Repos\NecroBot\PoGo.NecroBot.Logic\Common\ApiFailureStrategy.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

### Your config.json
default config.json

### Steps to Reproduce
Not sure, just occured like that

### Other Information
Version: 0.8.5
Windows Version: 10
affected: catch, transfer, evolve, recycle, snipe, powerup/levelup, other, must restart the bot.

**Comment by 3HMonkey** [comment]
try updating to 0.8.6
