### ISSUE TITLE
Default setup broken

### ISSUE THREAD

**Issue by bennextmitchell** [NECROBOTIO/NecroBot#5497]
[11:00:32] () Exception caught, writing LogBuffer.

Unhandled Exception: System.TypeInitializationException: The type initializer fo
r 'PokemonGo.RocketAPI.HttpClient.PokemonHttpClient' threw an exception. ---> Sy
stem.TypeLoadException: Could not load type 'System.Security.Authentication.SslP
rotocols' from assembly 'System.Net.Primitives, Version=4.0.0.0, Culture=neutral
, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Net.Http.HttpClientHandler..ctor()
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..cctor()
   --- End of inner exception stack trace ---
   at PokemonGo.RocketAPI.HttpClient.PokemonHttpClient..ctor()
   at PokemonGo.RocketAPI.Client..ctor(ISettings settings, IApiFailureStrategy a
piFailureStrategy)
   at PoGo.NecroBot.Logic.State.Session.Reset(ISettings settings, ILogicSettings
 logicSettings)
   at PoGo.NecroBot.Logic.State.Session..ctor(ISettings settings, ILogicSettings
 logicSettings)
   at PoGo.NecroBot.CLI.Program.Main(String[] args)

**Comment by bennextmitchell** [comment]
Solved: servers are down.

**Comment by recon88** [comment]
Please use the proper template instead of removing it
